version: 1

# Default
formats: []

python:
  version: 3.6
  install:
    - method: setuptools
      path: package
  system_packages: true

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true
