"""`UKSIC2003 Standard <https://github.com/companieshouse/api-enumerations/blob/master/constants.yml>`_.

United Kingdom Standard Industrial Classification of Economic Activities 2003: the 4-digit codes that Companies House still
carries for companies registered before SIC 2007 (``sic_descriptions`` in the Companies House api-enumerations), with the
Companies House descriptions.

UK SIC 2003 corresponds to NACE Rev. 1.1 (``7487`` is NACE1 ``74.87``), but this is the list as Companies House carries it,
not a clean copy of the classification, so not every code is a NACE1 class. Of the 534 codes, 399 map to a NACE1 class, 110
to a NACE1 group and 8 to a NACE1 division, and 17 have no NACE1 equivalent, including the Companies House specific values
``7499`` (non-trading company), ``9800`` (residents property management) and ``9999`` (dormant company). See
:data:`pyisic.UKSIC2003_to_NACE1`.
"""

from ...types import Category, Classification, Standard, Standards

UKSIC2003 = Standard(
    standard=Standards.UKSIC2003,
    classes=[
        Classification("0111", "Grow cereals & other crops", Category.CLASS),
        Classification("0112", "Grow vegetables & nursery products", Category.CLASS),
        Classification("0113", "Grow fruit, nuts, beverage & spice crops", Category.CLASS),
        Classification("0121", "Farming of cattle, dairy farming", Category.CLASS),
        Classification("0122", "Farm sheep, goats, horses, etc.", Category.CLASS),
        Classification("0123", "Farming of swine", Category.CLASS),
        Classification("0124", "Farming of poultry", Category.CLASS),
        Classification("0125", "Other farming of animals", Category.CLASS),
        Classification("0130", "Crops combined with animals, mixed farms", Category.CLASS),
        Classification("0141", "Agricultural service activities", Category.CLASS),
        Classification("0142", "Animal husbandry services, not vets", Category.CLASS),
        Classification("0150", "Hunting and game rearing inc. services", Category.CLASS),
        Classification("0201", "Forestry & logging", Category.CLASS),
        Classification("0202", "Forestry & logging related services", Category.CLASS),
        Classification("0501", "Fishing", Category.CLASS),
        Classification("0502", "Operation of fish hatcheries & farms", Category.CLASS),
        Classification("1010", "Mining & agglomeration of hard coal", Category.CLASS),
        Classification("1020", "Mining and agglomeration of lignite", Category.CLASS),
        Classification("1030", "Extraction and agglomeration of peat", Category.CLASS),
        Classification("1110", "Extraction petroleum & natural gas", Category.CLASS),
        Classification("1120", "Services to oil and gas extraction", Category.CLASS),
        Classification("1200", "Mining of uranium & thorium ores", Category.CLASS),
        Classification("1310", "Mining of iron ores", Category.CLASS),
        Classification("1320", "Mining non-ferrous metal ores", Category.CLASS),
        Classification("1411", "Quarrying of stone for construction", Category.CLASS),
        Classification("1412", "Quarry of limestone, gypsum & chalk", Category.CLASS),
        Classification("1413", "Quarrying of slate", Category.CLASS),
        Classification("1421", "Operation of gravel and sand pits", Category.CLASS),
        Classification("1422", "Mining of clays and kaolin", Category.CLASS),
        Classification("1430", "Mine chemical & fertiliser minerals", Category.CLASS),
        Classification("1440", "Production of salt", Category.CLASS),
        Classification("1450", "Other mining and quarrying", Category.CLASS),
        Classification("1511", "Production and preserving of meat", Category.CLASS),
        Classification("1512", "Production & preserve poultry meat", Category.CLASS),
        Classification("1513", "Production meat & poultry products", Category.CLASS),
        Classification("1520", "Process & preserve fish & products", Category.CLASS),
        Classification("1531", "Processing & preserve potatoes", Category.CLASS),
        Classification("1532", "Manufacture of fruit & vegetable juice", Category.CLASS),
        Classification("1533", "Process etc. fruit, vegetables", Category.CLASS),
        Classification("1541", "Manufacture of crude oils and fats", Category.CLASS),
        Classification("1542", "Manufacture of refined oils & fats", Category.CLASS),
        Classification("1543", "Manufacture margarine & similar edible fats", Category.CLASS),
        Classification("1551", "Operation dairies & cheese making", Category.CLASS),
        Classification("1552", "Manufacture of ice cream", Category.CLASS),
        Classification("1561", "Manufacture of grain mill products", Category.CLASS),
        Classification("1562", "Manufacture of starches & starch products", Category.CLASS),
        Classification("1571", "Manufacture of prepared farm animal feeds", Category.CLASS),
        Classification("1572", "Manufacture of prepared pet foods", Category.CLASS),
        Classification("1581", "Manufacture of bread, fresh pastry & cakes", Category.CLASS),
        Classification("1582", "Manufacture biscuits, preserved pastry etc.", Category.CLASS),
        Classification("1583", "Manufacture of sugar", Category.CLASS),
        Classification("1584", "Manufacture cocoa, chocolate, confectionery", Category.CLASS),
        Classification("1585", "Manufacture macaroni & similar farinaceous", Category.CLASS),
        Classification("1586", "Processing of tea and coffee", Category.CLASS),
        Classification("1587", "Manufacture of condiments & seasonings", Category.CLASS),
        Classification("1588", "Manufacture of homogenised & dietetic food", Category.CLASS),
        Classification("1589", "Manufacture of other food products", Category.CLASS),
        Classification("1591", "Manufacture distilled potable alcoholic drinks", Category.CLASS),
        Classification("1592", "Ethyl alcohol fermented materials", Category.CLASS),
        Classification("1593", "Manufacture of wines", Category.CLASS),
        Classification("1594", "Manufacture of cider & other fruit wines", Category.CLASS),
        Classification("1595", "Manufacture other non-distilled fermented drinks", Category.CLASS),
        Classification("1596", "Manufacture of beer", Category.CLASS),
        Classification("1597", "Manufacture of malt", Category.CLASS),
        Classification("1598", "Produce mineral water, soft drinks", Category.CLASS),
        Classification("1600", "Manufacture of tobacco products", Category.CLASS),
        Classification("1711", "Prepare & spin cotton-type fibres", Category.CLASS),
        Classification("1712", "Prepare & spin woollen-type fibres", Category.CLASS),
        Classification("1713", "Prepare & spin worsted-type fibres", Category.CLASS),
        Classification("1714", "Preparation & spin flax-type fibres", Category.CLASS),
        Classification("1715", "Throw & prepare silk, synthetic etc.", Category.CLASS),
        Classification("1716", "Manufacture of sewing threads", Category.CLASS),
        Classification("1717", "Preparation & spin of other textiles", Category.CLASS),
        Classification("1721", "Cotton-type weaving", Category.CLASS),
        Classification("1722", "Woollen-type weaving", Category.CLASS),
        Classification("1723", "Worsted-type weaving", Category.CLASS),
        Classification("1724", "Silk-type weaving", Category.CLASS),
        Classification("1725", "Other textile weaving", Category.CLASS),
        Classification("1730", "Finishing of textiles", Category.CLASS),
        Classification("1740", "Manufacture made-up textiles, not apparel", Category.CLASS),
        Classification("1751", "Manufacture of carpet and rugs", Category.CLASS),
        Classification("1752", "Manufacture cordage, rope, twine & netting", Category.CLASS),
        Classification("1753", "Manufacture nonwovens & goods, not apparel", Category.CLASS),
        Classification("1754", "Manufacture of other textiles", Category.CLASS),
        Classification("1760", "Manufacture of knitted & crocheted fabrics", Category.CLASS),
        Classification("1771", "Manufacture of knitted & crocheted hosiery", Category.CLASS),
        Classification("1772", "Manufacture knit & crocheted pullovers, etc.", Category.CLASS),
        Classification("1810", "Manufacture of leather clothes", Category.CLASS),
        Classification("1821", "Manufacture of workwear", Category.CLASS),
        Classification("1822", "Manufacture of other outerwear", Category.CLASS),
        Classification("1823", "Manufacture of underwear", Category.CLASS),
        Classification("1824", "Manufacture other wearing apparel etc.", Category.CLASS),
        Classification("1830", "Dress & dye fur; manufacture fur articles", Category.CLASS),
        Classification("1910", "Tanning and dressing of leather", Category.CLASS),
        Classification("1920", "Manufacture of luggage & the like, saddlery", Category.CLASS),
        Classification("1930", "Manufacture of footwear", Category.CLASS),
        Classification("2010", "Sawmill, plane, impregnation wood", Category.CLASS),
        Classification("2020", "Manufacture of veneer sheets, plywood, etc.", Category.CLASS),
        Classification("2030", "Manufacture builders carpentry & joinery", Category.CLASS),
        Classification("2040", "Manufacture of wooden containers", Category.CLASS),
        Classification("2051", "Manufacture of other products of wood", Category.CLASS),
        Classification("2052", "Manufacture of articles of cork, straw etc.", Category.CLASS),
        Classification("2111", "Manufacture of pulp", Category.CLASS),
        Classification("2112", "Manufacture of paper & paperboard", Category.CLASS),
        Classification("2121", "Manufacture of cartons", Category.CLASS),
        Classification("2122", "Manufacture of household & toilet goods", Category.CLASS),
        Classification("2123", "Manufacture of paper stationery", Category.CLASS),
        Classification("2124", "Manufacture of wallpaper", Category.CLASS),
        Classification("2125", "Manufacture of paper & paperboard goods", Category.CLASS),
        Classification("2211", "Publishing of books", Category.CLASS),
        Classification("2212", "Publishing of newspapers", Category.CLASS),
        Classification("2213", "Publish journals & periodicals", Category.CLASS),
        Classification("2214", "Publishing of sound recordings", Category.CLASS),
        Classification("2215", "Other publishing", Category.CLASS),
        Classification("2221", "Printing of newspapers", Category.CLASS),
        Classification("2222", "Printing not elsewhere classified", Category.CLASS),
        Classification("2223", "Bookbinding and finishing", Category.CLASS),
        Classification("2224", "Pre-press activities", Category.CLASS),
        Classification("2225", "Ancillary printing operations", Category.CLASS),
        Classification("2231", "Reproduction of sound recording", Category.CLASS),
        Classification("2232", "Reproduction of video recording", Category.CLASS),
        Classification("2233", "Reproduction of computer media", Category.CLASS),
        Classification("2310", "Manufacture of coke oven products", Category.CLASS),
        Classification("2320", "Manufacture of refined petroleum products", Category.CLASS),
        Classification("2330", "Processing of nuclear fuel", Category.CLASS),
        Classification("2411", "Manufacture of industrial gases", Category.CLASS),
        Classification("2412", "Manufacture of dyes and pigments", Category.CLASS),
        Classification("2413", "Manufacture other inorganic basic chemicals", Category.CLASS),
        Classification("2414", "Manufacture other organic basic chemicals", Category.CLASS),
        Classification("2415", "Manufacture fertilisers, nitrogen compounds", Category.CLASS),
        Classification("2416", "Manufacture of plastics in primary forms", Category.CLASS),
        Classification("2417", "Manufacture synthetic rubber primary forms", Category.CLASS),
        Classification("2420", "Manufacture of pesticides & agro-chemicals", Category.CLASS),
        Classification("2430", "Manufacture of paints, print ink & mastics etc.", Category.CLASS),
        Classification("2441", "Manufacture of basic pharmaceutical prods", Category.CLASS),
        Classification("2442", "Manufacture of pharmaceutical preparations", Category.CLASS),
        Classification("2451", "Manufacture soap & detergents, polishes etc.", Category.CLASS),
        Classification("2452", "Manufacture perfumes & toilet preparations", Category.CLASS),
        Classification("2461", "Manufacture of explosives", Category.CLASS),
        Classification("2462", "Manufacture of glues and gelatines", Category.CLASS),
        Classification("2463", "Manufacture of essential oils", Category.CLASS),
        Classification("2464", "Manufacture photograph chemical material", Category.CLASS),
        Classification("2465", "Manufacture of prepared unrecorded media", Category.CLASS),
        Classification("2466", "Manufacture of other chemical products", Category.CLASS),
        Classification("2470", "Manufacture of man-made fibres", Category.CLASS),
        Classification("2511", "Manufacture of rubber tyres & tubes", Category.CLASS),
        Classification("2512", "Retread & rebuild rubber tyres", Category.CLASS),
        Classification("2513", "Manufacture of other rubber products", Category.CLASS),
        Classification("2521", "Manufacture of plastic plates, sheets, etc.", Category.CLASS),
        Classification("2522", "Manufacture of plastic pack goods", Category.CLASS),
        Classification("2523", "Manufacture of builders ware of plastic", Category.CLASS),
        Classification("2524", "Manufacture of other plastic products", Category.CLASS),
        Classification("2611", "Manufacture of flat glass", Category.CLASS),
        Classification("2612", "Shaping & process of flat glass", Category.CLASS),
        Classification("2613", "Manufacture of hollow glass", Category.CLASS),
        Classification("2614", "Manufacture of glass fibres", Category.CLASS),
        Classification("2615", "Manufacture other glass inc. technical", Category.CLASS),
        Classification("2621", "Manufacture of ceramic household etc. goods", Category.CLASS),
        Classification("2622", "Manufacture of ceramic sanitary fixtures", Category.CLASS),
        Classification("2623", "Manufacture of ceramic insulators etc.", Category.CLASS),
        Classification("2624", "Manufacture other technical ceramic goods", Category.CLASS),
        Classification("2625", "Manufacture of other ceramic products", Category.CLASS),
        Classification("2626", "Manufacture of refractory ceramic products", Category.CLASS),
        Classification("2630", "Manufacture of ceramic tiles & flags", Category.CLASS),
        Classification("2640", "Manufacture of bricks, etc. in baked clay", Category.CLASS),
        Classification("2651", "Manufacture of cement", Category.CLASS),
        Classification("2652", "Manufacture of lime", Category.CLASS),
        Classification("2653", "Manufacture of plaster", Category.CLASS),
        Classification("2661", "Manufacture concrete goods for construction", Category.CLASS),
        Classification("2662", "Manufacture plaster goods for construction", Category.CLASS),
        Classification("2663", "Manufacture of ready-mixed concrete", Category.CLASS),
        Classification("2664", "Manufacture of mortars", Category.CLASS),
        Classification("2665", "Manufacture of fibre cement", Category.CLASS),
        Classification("2666", "Manufacture other articles of concrete, etc.", Category.CLASS),
        Classification("2670", "Cutting, shaping & finish stone", Category.CLASS),
        Classification("2681", "Production of abrasive products", Category.CLASS),
        Classification("2682", "Manufacture other non-metal mineral", Category.CLASS),
        Classification("2710", "Manufacture of basic iron & steel & of Ferro-alloys", Category.CLASS),
        Classification("2721", "Manufacture of cast iron tubes", Category.CLASS),
        Classification("2722", "Manufacture of steel tubes", Category.CLASS),
        Classification("2731", "Cold drawing", Category.CLASS),
        Classification("2732", "Cold rolling of narrow strips", Category.CLASS),
        Classification("2733", "Cold forming or folding", Category.CLASS),
        Classification("2734", "Wire drawing", Category.CLASS),
        Classification("2735", "Other 1st process iron & steel", Category.CLASS),
        Classification("2741", "Precious metals production", Category.CLASS),
        Classification("2742", "Aluminium production", Category.CLASS),
        Classification("2743", "Lead, zinc and tin production", Category.CLASS),
        Classification("2744", "Copper production", Category.CLASS),
        Classification("2745", "Other non-ferrous metal production", Category.CLASS),
        Classification("2751", "Casting of iron", Category.CLASS),
        Classification("2752", "Casting of steel", Category.CLASS),
        Classification("2753", "Casting of light metals", Category.CLASS),
        Classification("2754", "Casting of other non-ferrous metals", Category.CLASS),
        Classification("2811", "Manufacture metal structures & parts", Category.CLASS),
        Classification("2812", "Manufacture builders carpentry of metal", Category.CLASS),
        Classification("2821", "Manufacture tanks, etc. & metal containers", Category.CLASS),
        Classification("2822", "Manufacture central heating rads & boilers", Category.CLASS),
        Classification("2830", "Manufacture steam generators, not boilers", Category.CLASS),
        Classification("2840", "Forge press stamp & roll form metal", Category.CLASS),
        Classification("2851", "Treatment and coat metals", Category.CLASS),
        Classification("2852", "General mechanical engineering", Category.CLASS),
        Classification("2861", "Manufacture of cutlery", Category.CLASS),
        Classification("2862", "Manufacture of tools", Category.CLASS),
        Classification("2863", "Manufacture of locks and hinges", Category.CLASS),
        Classification("2871", "Manufacture steel drums, similar containers", Category.CLASS),
        Classification("2872", "Manufacture of light metal packaging", Category.CLASS),
        Classification("2873", "Manufacture of wire products", Category.CLASS),
        Classification("2874", "Manufacture fasteners, screw, chains etc.", Category.CLASS),
        Classification("2875", "Manufacture other fabricated metal products", Category.CLASS),
        Classification("2911", "Manufacture engines, not aircraft, etc.", Category.CLASS),
        Classification("2912", "Manufacture of pumps & compressors", Category.CLASS),
        Classification("2913", "Manufacture of taps and valves", Category.CLASS),
        Classification("2914", "Manufacture bearings, gears, gear etc.", Category.CLASS),
        Classification("2921", "Manufacture of furnaces & furnace burners", Category.CLASS),
        Classification("2922", "Manufacture of lift & handling equipment", Category.CLASS),
        Classification("2923", "Manufacture non-domestic ventilation", Category.CLASS),
        Classification("2924", "Manufacture of other general machinery", Category.CLASS),
        Classification("2931", "Manufacture of agricultural tractors", Category.CLASS),
        Classification("2932", "Manufacture other agric. & forestry machines", Category.CLASS),
        Classification("2940", "Manufacture of machine tools", Category.CLASS),
        Classification("2941", "Manufacture of portable hand held power tools", Category.CLASS),
        Classification("2942", "Manufacture of metalworking tools", Category.CLASS),
        Classification("2943", "Manufacture of other machine tools not elsewhere classified", Category.CLASS),
        Classification("2951", "Manufacture of machinery for metallurgy", Category.CLASS),
        Classification("2952", "Manufacture machines for mining, quarry etc.", Category.CLASS),
        Classification("2953", "Manufacture for food, beverage & tobacco", Category.CLASS),
        Classification("2954", "Manufacture for textile, apparel & leather", Category.CLASS),
        Classification("2955", "Manufacture machinery for paper & board", Category.CLASS),
        Classification("2956", "Manufacture other special purpose machine", Category.CLASS),
        Classification("2960", "Manufacture of weapons & ammunition", Category.CLASS),
        Classification("2971", "Manufacture of electric domestic appliances", Category.CLASS),
        Classification("2972", "Manufacture non-electric domestic appliances", Category.CLASS),
        Classification("3001", "Manufacture of office machinery", Category.CLASS),
        Classification("3002", "Manufacture computers & process equipment", Category.CLASS),
        Classification("3110", "Manufacture electric motors, generators etc.", Category.CLASS),
        Classification("3120", "Manufacture electricity distribution etc.", Category.CLASS),
        Classification("3130", "Manufacture of insulated wire & cable", Category.CLASS),
        Classification("3140", "Manufacture of accumulators, batteries etc.", Category.CLASS),
        Classification("3150", "Manufacture lighting equipment & lamps", Category.CLASS),
        Classification("3161", "Manufacture electric equipment, engines etc.", Category.CLASS),
        Classification("3162", "Manufacture other electrical equipment", Category.CLASS),
        Classification("3210", "Manufacture of electronic components", Category.CLASS),
        Classification("3220", "Manufacture TV transmitters, telephony etc.", Category.CLASS),
        Classification("3230", "Manufacture TV & radio, sound or video etc.", Category.CLASS),
        Classification("3310", "Manufacture medical, orthopaedic etc. equipment", Category.CLASS),
        Classification("3320", "Manufacture instruments for measuring etc.", Category.CLASS),
        Classification("3330", "Manufacture indust process control equipment", Category.CLASS),
        Classification("3340", "Manufacture optical, photographic etc. equipment", Category.CLASS),
        Classification("3350", "Manufacture of watches and clocks", Category.CLASS),
        Classification("3410", "Manufacture of motor vehicles", Category.CLASS),
        Classification("3420", "Manufacture motor vehicle bodies etc.", Category.CLASS),
        Classification("3430", "Manufacture motor vehicle & engine parts", Category.CLASS),
        Classification("3511", "Building and repairing of ships", Category.CLASS),
        Classification("3512", "Build & repair pleasure & sport boats", Category.CLASS),
        Classification("3520", "Manufacture of railway locomotives & stock", Category.CLASS),
        Classification("3530", "Manufacture of aircraft & spacecraft", Category.CLASS),
        Classification("3541", "Manufacture of motorcycles", Category.CLASS),
        Classification("3542", "Manufacture of bicycles", Category.CLASS),
        Classification("3543", "Manufacture of invalid carriages", Category.CLASS),
        Classification("3550", "Manufacture other transport equipment", Category.CLASS),
        Classification("3611", "Manufacture of chairs and seats", Category.CLASS),
        Classification("3612", "Manufacture other office & shop furniture", Category.CLASS),
        Classification("3613", "Manufacture of other kitchen furniture", Category.CLASS),
        Classification("3614", "Manufacture of other furniture", Category.CLASS),
        Classification("3615", "Manufacture of mattresses", Category.CLASS),
        Classification("3621", "Striking of coins and medals", Category.CLASS),
        Classification("3622", "Manufacture of jewellery & related", Category.CLASS),
        Classification("3630", "Manufacture of musical instruments", Category.CLASS),
        Classification("3640", "Manufacture of sports goods", Category.CLASS),
        Classification("3650", "Manufacture of games and toys", Category.CLASS),
        Classification("3661", "Manufacture of imitation jewellery", Category.CLASS),
        Classification("3662", "Manufacture of brooms and brushes", Category.CLASS),
        Classification("3663", "Other manufacturing", Category.CLASS),
        Classification("3710", "Recycling of metal waste and scrap", Category.CLASS),
        Classification("3720", "Recycling non-metal waste & scrap", Category.CLASS),
        Classification("4010", "Production", Category.CLASS),
        Classification("4011", "Production of electricity", Category.CLASS),
        Classification("4012", "Transmission of electricity", Category.CLASS),
        Classification("4013", "Distribution & trade in electricity", Category.CLASS),
        Classification("4020", "Mfr of gas; mains distribution", Category.CLASS),
        Classification("4021", "Manufacture of gas", Category.CLASS),
        Classification("4022", "Distribution & trade of gaseous fuels through mains", Category.CLASS),
        Classification("4030", "Steam and hot water supply", Category.CLASS),
        Classification("4100", "Collection, purify etc. of water", Category.CLASS),
        Classification("4511", "Demolition buildings; earth moving", Category.CLASS),
        Classification("4512", "Test drilling and boring", Category.CLASS),
        Classification("4521", "General construction & civil engineer", Category.CLASS),
        Classification("4522", "Erection of roof covering & frames", Category.CLASS),
        Classification("4523", "Construction roads, airfields etc.", Category.CLASS),
        Classification("4524", "Construction of water projects", Category.CLASS),
        Classification("4525", "Other special trades construction", Category.CLASS),
        Classification("4531", "Installation electrical wiring etc.", Category.CLASS),
        Classification("4532", "Insulation work activities", Category.CLASS),
        Classification("4533", "Plumbing", Category.CLASS),
        Classification("4534", "Other building installation", Category.CLASS),
        Classification("4541", "Plastering", Category.CLASS),
        Classification("4542", "Joinery installation", Category.CLASS),
        Classification("4543", "Floor and wall covering", Category.CLASS),
        Classification("4544", "Painting and glazing", Category.CLASS),
        Classification("4545", "Other building completion", Category.CLASS),
        Classification("4550", "Rent construction equipment with operator", Category.CLASS),
        Classification("5010", "Sale of motor vehicles", Category.CLASS),
        Classification("5020", "Maintenance & repair of motors", Category.CLASS),
        Classification("5030", "Sale of motor vehicle parts etc.", Category.CLASS),
        Classification("5040", "Sale, repair etc. motorcycles & parts", Category.CLASS),
        Classification("5050", "Retail sale of automotive fuel", Category.CLASS),
        Classification("5111", "Agents agric & textile materials", Category.CLASS),
        Classification("5112", "Agents in sale of fuels, ores, etc.", Category.CLASS),
        Classification("5113", "Agents in building materials", Category.CLASS),
        Classification("5114", "Agents in industrial equipment, etc.", Category.CLASS),
        Classification("5115", "Agents in household goods, etc.", Category.CLASS),
        Classification("5116", "Agents in textiles, footwear etc.", Category.CLASS),
        Classification("5117", "Agents in food, drink & tobacco", Category.CLASS),
        Classification("5118", "Agents in particular products", Category.CLASS),
        Classification("5119", "Agents in sale of variety of goods", Category.CLASS),
        Classification("5121", "Wholesale of grain, animal feeds", Category.CLASS),
        Classification("5122", "Wholesale of flowers and plants", Category.CLASS),
        Classification("5123", "Wholesale of live animals", Category.CLASS),
        Classification("5124", "Wholesale hides, skins and leather", Category.CLASS),
        Classification("5125", "Wholesale of unmanufactured tobacco", Category.CLASS),
        Classification("5131", "Wholesale of fruit and vegetables", Category.CLASS),
        Classification("5132", "Wholesale of meat and meat products", Category.CLASS),
        Classification("5133", "Wholesale dairy products", Category.CLASS),
        Classification("5134", "Wholesale of alcohol and other drinks", Category.CLASS),
        Classification("5135", "Wholesale of tobacco products", Category.CLASS),
        Classification("5136", "Wholesale sugar, chocolate etc.", Category.CLASS),
        Classification("5137", "Wholesale coffee, tea, cocoa etc.", Category.CLASS),
        Classification("5138", "Wholesale other food inc fish, etc.", Category.CLASS),
        Classification("5139", "Non-specialised wholesale food, etc.", Category.CLASS),
        Classification("5141", "Wholesale of textiles", Category.CLASS),
        Classification("5142", "Wholesale of clothing and footwear", Category.CLASS),
        Classification("5143", "Wholesale electric household goods", Category.CLASS),
        Classification("5144", "Wholesale of china, wallpaper etc.", Category.CLASS),
        Classification("5145", "Wholesale of perfume and cosmetics", Category.CLASS),
        Classification("5146", "Wholesale of pharmaceutical goods", Category.CLASS),
        Classification("5147", "Wholesale of other household goods", Category.CLASS),
        Classification("5151", "Wholesale fuels & related products", Category.CLASS),
        Classification("5152", "Wholesale of metals and metal ores", Category.CLASS),
        Classification("5153", "Wholesale wood, construction etc.", Category.CLASS),
        Classification("5154", "Wholesale hardware, plumbing etc.", Category.CLASS),
        Classification("5155", "Wholesale of chemical products", Category.CLASS),
        Classification("5156", "Wholesale other intermediate goods", Category.CLASS),
        Classification("5157", "Wholesale of waste and scrap", Category.CLASS),
        Classification("5161", "Wholesale of machine tools", Category.CLASS),
        Classification("5162", "Wholesale of construction machinery", Category.CLASS),
        Classification("5163", "Wholesale textile industry machines", Category.CLASS),
        Classification("5164", "Wholesale office machinery & equip", Category.CLASS),
        Classification("5165", "Wholesale machines", Category.CLASS),
        Classification("5166", "Wholesale agric machines & tractors", Category.CLASS),
        Classification("5170", "Other wholesale", Category.CLASS),
        Classification("5181", "Wholesale of machine tools", Category.CLASS),
        Classification("5182", "Wholesale of mining", Category.CLASS),
        Classification("5183", "Wholesale of machinery for the textile industry", Category.CLASS),
        Classification("5184", "Wholesale of computers", Category.CLASS),
        Classification("5185", "Wholesale of other office machinery & equipment", Category.CLASS),
        Classification("5186", "Wholesale of other electronic parts & equipment", Category.CLASS),
        Classification("5187", "Wholesale of other machinery for use in industry", Category.CLASS),
        Classification("5188", "Wholesale of agricultural machinery & accessories & implements", Category.CLASS),
        Classification("5190", "Other wholesale", Category.CLASS),
        Classification("5211", "Retail in non-specialised stores holding an alcohol licence", Category.CLASS),
        Classification("5212", "Other retail non-specialised stores", Category.CLASS),
        Classification("5221", "Retail of fruit and vegetables", Category.CLASS),
        Classification("5222", "Retail of meat and meat products", Category.CLASS),
        Classification("5223", "Retail of fish, crustaceans etc.", Category.CLASS),
        Classification("5224", "Retail bread, cakes, confectionery", Category.CLASS),
        Classification("5225", "Retail alcoholic & other beverages", Category.CLASS),
        Classification("5226", "Retail sale of tobacco products", Category.CLASS),
        Classification("5227", "Other retail food etc. specialised", Category.CLASS),
        Classification("5231", "Dispensing chemists", Category.CLASS),
        Classification("5232", "Retail medical & orthopaedic goods", Category.CLASS),
        Classification("5233", "Retail cosmetic & toilet articles", Category.CLASS),
        Classification("5241", "Retail sale of textiles", Category.CLASS),
        Classification("5242", "Retail sale of clothing", Category.CLASS),
        Classification("5243", "Retail of footwear & leather goods", Category.CLASS),
        Classification("5244", "Retail furniture household etc", Category.CLASS),
        Classification("5245", "Retail electric household, etc. goods", Category.CLASS),
        Classification("5246", "Retail hardware, paints & glass", Category.CLASS),
        Classification("5247", "Retail books, newspapers etc.", Category.CLASS),
        Classification("5248", "Other retail specialist stores", Category.CLASS),
        Classification("5250", "Retail other secondhand goods", Category.CLASS),
        Classification("5261", "Retail sale via mail order houses", Category.CLASS),
        Classification("5262", "Retail sale via stalls and markets", Category.CLASS),
        Classification("5263", "Other non-store retail sale", Category.CLASS),
        Classification("5271", "Repair boots, shoes, leather goods", Category.CLASS),
        Classification("5272", "Repair electrical household goods", Category.CLASS),
        Classification("5273", "Repair of clocks & jewellery", Category.CLASS),
        Classification("5274", "Repair not elsewhere classified", Category.CLASS),
        Classification("5510", "Hotels & motels with or without restaurant", Category.CLASS),
        Classification("5511", "Hotels & motels", Category.CLASS),
        Classification("5512", "Hotels & motels", Category.CLASS),
        Classification("5521", "Youth hostels and mountain refuges", Category.CLASS),
        Classification("5522", "Camp sites, including caravan sites", Category.CLASS),
        Classification("5523", "Other provision of lodgings", Category.CLASS),
        Classification("5530", "Restaurants", Category.CLASS),
        Classification("5540", "Bars", Category.CLASS),
        Classification("5551", "Canteens", Category.CLASS),
        Classification("5552", "Catering", Category.CLASS),
        Classification("6010", "Transport via railways", Category.CLASS),
        Classification("6021", "Other scheduled passenger land transport", Category.CLASS),
        Classification("6022", "Taxi operation", Category.CLASS),
        Classification("6023", "Other passenger land transport", Category.CLASS),
        Classification("6024", "Freight transport by road", Category.CLASS),
        Classification("6030", "Transport via pipelines", Category.CLASS),
        Classification("6110", "Sea and coastal water transport", Category.CLASS),
        Classification("6120", "Inland water transport", Category.CLASS),
        Classification("6210", "Scheduled air transport", Category.CLASS),
        Classification("6220", "Non-scheduled air transport", Category.CLASS),
        Classification("6230", "Space transport", Category.CLASS),
        Classification("6311", "Cargo handling", Category.CLASS),
        Classification("6312", "Storage & warehousing", Category.CLASS),
        Classification("6321", "Other supporting land transport", Category.CLASS),
        Classification("6322", "Other supporting water transport", Category.CLASS),
        Classification("6323", "Other supporting air transport", Category.CLASS),
        Classification("6330", "Travel agencies etc; tourist", Category.CLASS),
        Classification("6340", "Other transport agencies", Category.CLASS),
        Classification("6411", "National post activities", Category.CLASS),
        Classification("6412", "Courier other than national post", Category.CLASS),
        Classification("6420", "Telecommunications", Category.CLASS),
        Classification("6511", "Central banking", Category.CLASS),
        Classification("6512", "Other monetary intermediation", Category.CLASS),
        Classification("6521", "Financial leasing", Category.CLASS),
        Classification("6522", "Other credit granting", Category.CLASS),
        Classification("6523", "Other financial intermediation", Category.CLASS),
        Classification("6601", "Life insurance/reinsurance", Category.CLASS),
        Classification("6602", "Pension funding", Category.CLASS),
        Classification("6603", "Non-life insurance/reinsurance", Category.CLASS),
        Classification("6711", "Administration of financial markets", Category.CLASS),
        Classification("6712", "Security broking & fund management", Category.CLASS),
        Classification("6713", "Auxiliary financial intermed", Category.CLASS),
        Classification("6720", "Auxiliary insurance & pension fund", Category.CLASS),
        Classification("7011", "Development & sell real estate", Category.CLASS),
        Classification("7012", "Buying & sell own real estate", Category.CLASS),
        Classification("7020", "Letting of own property", Category.CLASS),
        Classification("7031", "Real estate agencies", Category.CLASS),
        Classification("7032", "Manage real estate, fee or contract", Category.CLASS),
        Classification("7110", "Renting of automobiles", Category.CLASS),
        Classification("7121", "Rent other land transport equipment", Category.CLASS),
        Classification("7122", "Rent water transport equipment", Category.CLASS),
        Classification("7123", "Renting of air transport equipment", Category.CLASS),
        Classification("7131", "Rent agricultural machinery & equip", Category.CLASS),
        Classification("7132", "Rent civil engineering machinery", Category.CLASS),
        Classification("7133", "Rent office machinery inc computers", Category.CLASS),
        Classification("7134", "Rent other machinery & equip", Category.CLASS),
        Classification("7140", "Rent personal & household goods", Category.CLASS),
        Classification("7210", "Hardware consultancy", Category.CLASS),
        Classification("7220", "Software consultancy and supply", Category.CLASS),
        Classification("7221", "Software publishing", Category.CLASS),
        Classification("7222", "Other software consultancy and supply", Category.CLASS),
        Classification("7230", "Data processing", Category.CLASS),
        Classification("7240", "Data base activities", Category.CLASS),
        Classification("7250", "Maintenance office & computing mach", Category.CLASS),
        Classification("7260", "Other computer related activities", Category.CLASS),
        Classification("7310", "R & d on nat sciences & engineering", Category.CLASS),
        Classification("7320", "R & d on soc sciences & humanities", Category.CLASS),
        Classification("7411", "Legal activities", Category.CLASS),
        Classification("7412", "Accounting, auditing; tax consult", Category.CLASS),
        Classification("7413", "Market research, opinion polling", Category.CLASS),
        Classification("7414", "Business & management consultancy", Category.CLASS),
        Classification("7415", "Holding companies including Head Offices", Category.CLASS),
        Classification("7420", "Architectural, technical consult", Category.CLASS),
        Classification("7430", "Technical testing and analysis", Category.CLASS),
        Classification("7440", "Advertising", Category.CLASS),
        Classification("7450", "Labour recruitment", Category.CLASS),
        Classification("7460", "Investigation & security", Category.CLASS),
        Classification("7470", "Other cleaning activities", Category.CLASS),
        Classification("7481", "Portrait photographic activities", Category.CLASS),
        Classification("7482", "Packaging activities", Category.CLASS),
        Classification("7483", "Secretarial & translation", Category.CLASS),
        Classification("7484", "Other business activities", Category.CLASS),
        Classification("7485", "Secretarial & translation services", Category.CLASS),
        Classification("7486", "Call centre activities", Category.CLASS),
        Classification("7487", "Other business activities", Category.CLASS),
        Classification("7499", "Non-trading company", Category.CLASS),
        Classification("7511", "General (overall) public service", Category.CLASS),
        Classification("7512", "Regulation health, education, etc.", Category.CLASS),
        Classification("7513", "Regulation more efficient business", Category.CLASS),
        Classification("7514", "Support services for government", Category.CLASS),
        Classification("7521", "Foreign affairs", Category.CLASS),
        Classification("7522", "Defence activities", Category.CLASS),
        Classification("7523", "Justice and judicial activities", Category.CLASS),
        Classification("7524", "Public security, law & order", Category.CLASS),
        Classification("7525", "Fire service activities", Category.CLASS),
        Classification("7530", "Compulsory social security", Category.CLASS),
        Classification("8010", "Primary education", Category.CLASS),
        Classification("8021", "General secondary education", Category.CLASS),
        Classification("8022", "Technical & vocational secondary", Category.CLASS),
        Classification("8030", "Higher education", Category.CLASS),
        Classification("8041", "Driving school activities", Category.CLASS),
        Classification("8042", "Adult and other education", Category.CLASS),
        Classification("8511", "Hospital activities", Category.CLASS),
        Classification("8512", "Medical practice activities", Category.CLASS),
        Classification("8513", "Dental practice activities", Category.CLASS),
        Classification("8514", "Other human health activities", Category.CLASS),
        Classification("8520", "Veterinary activities", Category.CLASS),
        Classification("8531", "Social work with accommodation", Category.CLASS),
        Classification("8532", "Social work without accommodation", Category.CLASS),
        Classification("9000", "Refuse disposal", Category.CLASS),
        Classification("9001", "Collection and treatment of sewage", Category.CLASS),
        Classification("9002", "Collection and treatment of other waste", Category.CLASS),
        Classification("9003", "Sanitation remediation and similar activities", Category.CLASS),
        Classification("9111", "Business & employers organisations", Category.CLASS),
        Classification("9112", "Professional organisations", Category.CLASS),
        Classification("9120", "Trade unions", Category.CLASS),
        Classification("9131", "Religious organisations", Category.CLASS),
        Classification("9132", "Political organisations", Category.CLASS),
        Classification("9133", "Other membership organisations", Category.CLASS),
        Classification("9211", "Motion picture and video production", Category.CLASS),
        Classification("9212", "Motion picture & video distribution", Category.CLASS),
        Classification("9213", "Motion picture projection", Category.CLASS),
        Classification("9220", "Radio and television activities", Category.CLASS),
        Classification("9231", "Artistic & literary creation etc", Category.CLASS),
        Classification("9232", "Operation of arts facilities", Category.CLASS),
        Classification("9233", "Fair and amusement park activities", Category.CLASS),
        Classification("9234", "Other entertainment activities", Category.CLASS),
        Classification("9240", "News agency activities", Category.CLASS),
        Classification("9251", "Library and archives activities", Category.CLASS),
        Classification("9252", "Museum & preservation of history", Category.CLASS),
        Classification("9253", "Botanical, zoos & nature reserves", Category.CLASS),
        Classification("9261", "Operate sports arenas & stadiums", Category.CLASS),
        Classification("9262", "Other sporting activities", Category.CLASS),
        Classification("9271", "Gambling and betting activities", Category.CLASS),
        Classification("9272", "Other recreational activities nec", Category.CLASS),
        Classification("9301", "Wash & dry clean textile & fur", Category.CLASS),
        Classification("9302", "Hairdressing & other beauty treatment", Category.CLASS),
        Classification("9303", "Funeral and related activities", Category.CLASS),
        Classification("9304", "Physical well-being activities", Category.CLASS),
        Classification("9305", "Other service activities n.e.c.", Category.CLASS),
        Classification("9500", "Private household with employees", Category.CLASS),
        Classification(
            "9600", "Undifferentiated goods producing activities of private households for own use", Category.CLASS
        ),
        Classification(
            "9700", "Undifferentiated services producing activities of private households for own use", Category.CLASS
        ),
        Classification("9800", "Residents property management", Category.CLASS),
        Classification("9900", "Extra-territorial organisations", Category.CLASS),
        Classification("9999", "Dormant company", Category.CLASS),
    ],
)
