from ...types import Category, Classification, Standard, Standards

CNAE2 = Standard(
    standard=Standards.CNAE2,
    classes=[
        Classification("A", "AGRICULTURA, PECUÁRIA, PRODUÇÃO FLORESTAL, PESCA E AQÜICULTURA"),
        Classification("1", "AGRICULTURA, PECUÁRIA E SERVIÇOS RELACIONADOS"),
        Classification("1.1", "Produção de lavouras temporárias"),
        Classification("01.11-3", "Cultivo de cereais"),
        Classification("01.12-1", "Cultivo de algodão herbáceo e de outras fibras de lavoura temporária"),
        Classification("01.13-0", "Cultivo de cana-de-açúcar"),
        Classification("01.14-8", "Cultivo de fumo"),
        Classification("01.15-6", "Cultivo de soja"),
        Classification("01.16-4", "Cultivo de oleaginosas de lavoura temporária, exceto soja"),
        Classification("01.19-9", "Cultivo de plantas de lavoura temporária não especificadas anteriormente"),
        Classification("1.2", "Horticultura e floricultura"),
        Classification("01.21-1", "Horticultura"),
        Classification("01.22-9", "Cultivo de flores e plantas ornamentais"),
        Classification("1.3", "Produção de lavouras permanentes"),
        Classification("01.31-8", "Cultivo de laranja"),
        Classification("01.32-6", "Cultivo de uva"),
        Classification("01.33-4", "Cultivo de frutas de lavoura permanente, exceto laranja e uva"),
        Classification("01.34-2", "Cultivo de café"),
        Classification("01.35-1", "Cultivo de cacau"),
        Classification("01.39-3", "Cultivo de plantas de lavoura permanente não especificadas anteriormente"),
        Classification("1.4", "Produção de sementes e mudas certificadas"),
        Classification("01.41-5", "Produção de sementes certificadas"),
        Classification("01.42-3", "Produção de mudas e outras formas de propagação vegetal, certificadas"),
        Classification("1.5", "Pecuária"),
        Classification("01.51-2", "Criação de bovinos"),
        Classification("01.52-1", "Criação de outros animais de grande porte"),
        Classification("01.53-9", "Criação de caprinos e ovinos"),
        Classification("01.54-7", "Criação de suínos"),
        Classification("01.55-5", "Criação de aves"),
        Classification("01.59-8", "Criação de animais não especificados anteriormente"),
        Classification("1.6", "Atividades de apoio à agricultura e à pecuária; atividades de pós-colheita"),
        Classification("01.61-0", "Atividades de apoio à agricultura"),
        Classification("01.62-8", "Atividades de apoio à pecuária"),
        Classification("01.63-6", "Atividades de pós-colheita"),
        Classification("1.7", "Caça e serviços relacionados"),
        Classification("01.70-9", "Caça e serviços relacionados"),
        Classification("2", "PRODUÇÃO FLORESTAL"),
        Classification("2.1", "Produção florestal - florestas plantadas"),
        Classification("02.10-1", "Produção florestal - florestas plantadas"),
        Classification("2.2", "Produção florestal - florestas nativas"),
        Classification("02.20-9", "Produção florestal - florestas nativas"),
        Classification("2.3", "Atividades de apoio à produção florestal"),
        Classification("02.30-6", "Atividades de apoio à produção florestal"),
        Classification("3", "PESCA E AQÜICULTURA"),
        Classification("3.1", "Pesca"),
        Classification("03.11-6", "Pesca em água salgada"),
        Classification("03.12-4", "Pesca em água doce"),
        Classification("3.2", "Aqüicultura"),
        Classification("03.21-3", "Aqüicultura em água salgada e salobra"),
        Classification("03.22-1", "Aqüicultura em água doce"),
        Classification("B", "INDÚSTRIAS EXTRATIVAS"),
        Classification("5", "EXTRAÇÃO DE CARVÃO MINERAL"),
        Classification("5.0", "Extração de carvão mineral"),
        Classification("05.00-3", "Extração de carvão mineral"),
        Classification("6", "EXTRAÇÃO DE PETRÓLEO E GÁS NATURAL"),
        Classification("6.0", "Extração de petróleo e gás natural"),
        Classification("06.00-0", "Extração de petróleo e gás natural"),
        Classification("7", "EXTRAÇÃO DE MINERAIS METÁLICOS"),
        Classification("7.1", "Extração de minério de ferro"),
        Classification("07.10-3", "Extração de minério de ferro"),
        Classification("7.2", "Extração de minerais metálicos não-ferrosos"),
        Classification("07.21-9", "Extração de minério de alumínio"),
        Classification("07.22-7", "Extração de minério de estanho"),
        Classification("07.23-5", "Extração de minério de manganês"),
        Classification("07.24-3", "Extração de minério de metais preciosos"),
        Classification("07.25-1", "Extração de minerais radioativos"),
        Classification("07.29-4", "Extração de minerais metálicos não-ferrosos não especificados anteriormente"),
        Classification("8", "EXTRAÇÃO DE MINERAIS NÃO-METÁLICOS"),
        Classification("8.1", "Extração de pedra, areia e argila"),
        Classification("08.10-0", "Extração de pedra, areia e argila"),
        Classification("8.9", "Extração de outros minerais não-metálicos"),
        Classification(
            "08.91-6", "Extração de minerais para fabricação de adubos, fertilizantes e outros produtos químicos"
        ),
        Classification("08.92-4", "Extração e refino de sal marinho e sal-gema"),
        Classification("08.93-2", "Extração de gemas (pedras preciosas e semipreciosas)"),
        Classification("08.99-1", "Extração de minerais não-metálicos não especificados anteriormente"),
        Classification("9", "ATIVIDADES DE APOIO À EXTRAÇÃO DE MINERAIS"),
        Classification("9.1", "Atividades de apoio à extração de petróleo e gás natural"),
        Classification("09.10-6", "Atividades de apoio à extração de petróleo e gás natural"),
        Classification("9.9", "Atividades de apoio à extração de minerais, exceto petróleo e gás natural"),
        Classification("09.90-4", "Atividades de apoio à extração de minerais, exceto petróleo e gás natural"),
        Classification("C", "INDÚSTRIAS DE TRANSFORMAÇÃO"),
        Classification("10", "FABRICAÇÃO DE PRODUTOS ALIMENTÍCIOS"),
        Classification("10.1", "Abate e fabricação de produtos de carne"),
        Classification("10.11-2", "Abate de reses, exceto suínos"),
        Classification("10.12-1", "Abate de suínos, aves e outros pequenos animais"),
        Classification("10.13-9", "Fabricação de produtos de carne"),
        Classification("10.2", "Preservação do pescado e fabricação de produtos do pescado"),
        Classification("10.20-1", "Preservação do pescado e fabricação de produtos do pescado"),
        Classification("10.3", "Fabricação de conservas de frutas, legumes e outros vegetais"),
        Classification("10.31-7", "Fabricação de conservas de frutas"),
        Classification("10.32-5", "Fabricação de conservas de legumes e outros vegetais"),
        Classification("10.33-3", "Fabricação de sucos de frutas, hortaliças e legumes"),
        Classification("10.4", "Fabricação de óleos e gorduras vegetais e animais"),
        Classification("10.41-4", "Fabricação de óleos vegetais em bruto, exceto óleo de milho"),
        Classification("10.42-2", "Fabricação de óleos vegetais refinados, exceto óleo de milho"),
        Classification(
            "10.43-1", "Fabricação de margarina e outras gorduras vegetais e de óleos não-comestíveis de animais"
        ),
        Classification("10.5", "Laticínios"),
        Classification("10.51-1", "Preparação do leite"),
        Classification("10.52-0", "Fabricação de laticínios"),
        Classification("10.53-8", "Fabricação de sorvetes e outros gelados comestíveis"),
        Classification("10.6", "Moagem, fabricação de produtos amiláceos e de alimentos para animais"),
        Classification("10.61-9", "Beneficiamento de arroz e fabricação de produtos do arroz"),
        Classification("10.62-7", "Moagem de trigo e fabricação de derivados"),
        Classification("10.63-5", "Fabricação de farinha de mandioca e derivados"),
        Classification("10.64-3", "Fabricação de farinha de milho e derivados, exceto óleos de milho"),
        Classification("10.65-1", "Fabricação de amidos e féculas de vegetais e de óleos de milho"),
        Classification("10.66-0", "Fabricação de alimentos para animais"),
        Classification("10.69-4", "Moagem e fabricação de produtos de origem vegetal não especificados anteriormente"),
        Classification("10.7", "Fabricação e refino de açúcar"),
        Classification("10.71-6", "Fabricação de açúcar em bruto"),
        Classification("10.72-4", "Fabricação de açúcar refinado"),
        Classification("10.8", "Torrefação e moagem de café"),
        Classification("10.81-3", "Torrefação e moagem de café"),
        Classification("10.82-1", "Fabricação de produtos à base de café"),
        Classification("10.9", "Fabricação de outros produtos alimentícios"),
        Classification("10.91-1", "Fabricação de produtos de panificação"),
        Classification("10.92-9", "Fabricação de biscoitos e bolachas"),
        Classification("10.93-7", "Fabricação de produtos derivados do cacau, de chocolates e confeitos"),
        Classification("10.94-5", "Fabricação de massas alimentícias"),
        Classification("10.95-3", "Fabricação de especiarias, molhos, temperos e condimentos"),
        Classification("10.96-1", "Fabricação de alimentos e pratos prontos"),
        Classification("10.99-6", "Fabricação de produtos alimentícios não especificados anteriormente"),
        Classification("11", "FABRICAÇÃO DE BEBIDAS"),
        Classification("11.1", "Fabricação de bebidas alcoólicas"),
        Classification("11.11-9", "Fabricação de aguardentes e outras bebidas destiladas"),
        Classification("11.12-7", "Fabricação de vinho"),
        Classification("11.13-5", "Fabricação de malte, cervejas e chopes"),
        Classification("11.2", "Fabricação de bebidas não-alcoólicas"),
        Classification("11.21-6", "Fabricação de águas envasadas"),
        Classification("11.22-4", "Fabricação de refrigerantes e de outras bebidas não-alcoólicas"),
        Classification("12", "FABRICAÇÃO DE PRODUTOS DO FUMO"),
        Classification("12.1", "Processamento industrial do fumo"),
        Classification("12.10-7", "Processamento industrial do fumo"),
        Classification("12.2", "Fabricação de produtos do fumo"),
        Classification("12.20-4", "Fabricação de produtos do fumo"),
        Classification("13", "FABRICAÇÃO DE PRODUTOS TÊXTEIS"),
        Classification("13.1", "Preparação e fiação de fibras têxteis"),
        Classification("13.11-1", "Preparação e fiação de fibras de algodão"),
        Classification("13.12-0", "Preparação e fiação de fibras têxteis naturais, exceto algodão"),
        Classification("13.13-8", "Fiação de fibras artificiais e sintéticas"),
        Classification("13.14-6", "Fabricação de linhas para costurar e bordar"),
        Classification("13.2", "Tecelagem, exceto malha"),
        Classification("13.21-9", "Tecelagem de fios de algodão"),
        Classification("13.22-7", "Tecelagem de fios de fibras têxteis naturais, exceto algodão"),
        Classification("13.23-5", "Tecelagem de fios de fibras artificiais e sintéticas"),
        Classification("13.3", "Fabricação de tecidos de malha"),
        Classification("13.30-8", "Fabricação de tecidos de malha"),
        Classification("13.4", "Acabamentos em fios, tecidos e artefatos têxteis"),
        Classification("13.40-5", "Acabamentos em fios, tecidos e artefatos têxteis"),
        Classification("13.5", "Fabricação de artefatos têxteis, exceto vestuário"),
        Classification("13.51-1", "Fabricação de artefatos têxteis para uso doméstico"),
        Classification("13.52-9", "Fabricação de artefatos de tapeçaria"),
        Classification("13.53-7", "Fabricação de artefatos de cordoaria"),
        Classification("13.54-5", "Fabricação de tecidos especiais, inclusive artefatos"),
        Classification("13.59-6", "Fabricação de outros produtos têxteis não especificados anteriormente"),
        Classification("14", "CONFECÇÃO DE ARTIGOS DO VESTUÁRIO E ACESSÓRIOS"),
        Classification("14.1", "Confecção de artigos do vestuário e acessórios"),
        Classification("14.11-8", "Confecção de roupas íntimas"),
        Classification("14.12-6", "Confecção de peças do vestuário, exceto roupas íntimas"),
        Classification("14.13-4", "Confecção de roupas profissionais"),
        Classification("14.14-2", "Fabricação de acessórios do vestuário, exceto para segurança e proteção"),
        Classification("14.2", "Fabricação de artigos de malharia e tricotagem"),
        Classification("14.21-5", "Fabricação de meias"),
        Classification(
            "14.22-3", "Fabricação de artigos do vestuário, produzidos em malharias e tricotagens, exceto meias"
        ),
        Classification("15", "PREPARAÇÃO DE COUROS E FABRICAÇÃO DE ARTEFATOS DE COURO, ARTIGOS PARA VIAGEM E CALÇADOS"),
        Classification("15.1", "Curtimento e outras preparações de couro"),
        Classification("15.10-6", "Curtimento e outras preparações de couro"),
        Classification("15.2", "Fabricação de artigos para viagem e de artefatos diversos de couro"),
        Classification("15.21-1", "Fabricação de artigos para viagem, bolsas e semelhantes de qualquer material"),
        Classification("15.29-7", "Fabricação de artefatos de couro não especificados anteriormente"),
        Classification("15.3", "Fabricação de calçados"),
        Classification("15.31-9", "Fabricação de calçados de couro"),
        Classification("15.32-7", "Fabricação de tênis de qualquer material"),
        Classification("15.33-5", "Fabricação de calçados de material sintético"),
        Classification("15.39-4", "Fabricação de calçados de materiais não especificados anteriormente"),
        Classification("15.4", "Fabricação de partes para calçados, de qualquer material"),
        Classification("15.40-8", "Fabricação de partes para calçados, de qualquer material"),
        Classification("16", "FABRICAÇÃO DE PRODUTOS DE MADEIRA"),
        Classification("16.1", "Desdobramento de madeira"),
        Classification("16.10-2", "Desdobramento de madeira"),
        Classification("16.2", "Fabricação de produtos de madeira, cortiça e material trançado, exceto móveis"),
        Classification(
            "16.21-8", "Fabricação de madeira laminada e de chapas de madeira compensada, prensada e aglomerada"
        ),
        Classification("16.22-6", "Fabricação de estruturas de madeira e de artigos de carpintaria para construção"),
        Classification("16.23-4", "Fabricação de artefatos de tanoaria e de embalagens de madeira"),
        Classification(
            "16.29-3",
            "Fabricação de artefatos de madeira, palha, cortiça, vime e material trançado não especificados anteriormente, exceto móveis",
        ),
        Classification("17", "FABRICAÇÃO DE CELULOSE, PAPEL E PRODUTOS DE PAPEL"),
        Classification("17.1", "Fabricação de celulose e outras pastas para a fabricação de papel"),
        Classification("17.10-9", "Fabricação de celulose e outras pastas para a fabricação de papel"),
        Classification("17.2", "Fabricação de papel, cartolina e papel-cartão"),
        Classification("17.21-4", "Fabricação de papel"),
        Classification("17.22-2", "Fabricação de cartolina e papel-cartão"),
        Classification("17.3", "Fabricação de embalagens de papel, cartolina, papel-cartão e papelão ondulado"),
        Classification("17.31-1", "Fabricação de embalagens de papel"),
        Classification("17.32-0", "Fabricação de embalagens de cartolina e papel-cartão"),
        Classification("17.33-8", "Fabricação de chapas e de embalagens de papelão ondulado"),
        Classification("17.4", "Fabricação de produtos diversos de papel, cartolina, papel-cartão e papelão ondulado"),
        Classification(
            "17.41-9",
            "Fabricação de produtos de papel, cartolina, papel-cartão e papelão ondulado para uso comercial e de escritório",
        ),
        Classification("17.42-7", "Fabricação de produtos de papel para usos doméstico e higiênico-sanitário"),
        Classification(
            "17.49-4",
            "Fabricação de produtos de pastas celulósicas, papel, cartolina, papel-cartão e papelão ondulado não especificados anteriormente",
        ),
        Classification("18", "IMPRESSÃO E REPRODUÇÃO DE GRAVAÇÕES"),
        Classification("18.1", "Atividade de impressão"),
        Classification("18.11-3", "Impressão de jornais, livros, revistas e outras publicações periódicas"),
        Classification("18.12-1", "Impressão de material de segurança"),
        Classification("18.13-0", "Impressão de materiais para outros usos"),
        Classification("18.2", "Serviços de pré-impressão e acabamentos gráficos"),
        Classification("18.21-1", "Serviços de pré-impressão"),
        Classification("18.22-9", "Serviços de acabamentos gráficos"),
        Classification("18.3", "Reprodução de materiais gravados em qualquer suporte"),
        Classification("18.30-0", "Reprodução de materiais gravados em qualquer suporte"),
        Classification("19", "FABRICAÇÃO DE COQUE, DE PRODUTOS DERIVADOS DO PETRÓLEO E DE BIOCOMBUSTÍVEIS"),
        Classification("19.1", "Coquerias"),
        Classification("19.10-1", "Coquerias"),
        Classification("19.2", "Fabricação de produtos derivados do petróleo"),
        Classification("19.21-7", "Fabricação de produtos do refino de petróleo"),
        Classification("19.22-5", "Fabricação de produtos derivados do petróleo, exceto produtos do refino"),
        Classification("19.3", "Fabricação de biocombustíveis"),
        Classification("19.31-4", "Fabricação de álcool"),
        Classification("19.32-2", "Fabricação de biocombustíveis, exceto álcool"),
        Classification("20", "FABRICAÇÃO DE PRODUTOS QUÍMICOS"),
        Classification("20.1", "Fabricação de produtos químicos inorgânicos"),
        Classification("20.11-8", "Fabricação de cloro e álcalis"),
        Classification("20.12-6", "Fabricação de intermediários para fertilizantes"),
        Classification("20.13-4", "Fabricação de adubos e fertilizantes"),
        Classification("20.14-2", "Fabricação de gases industriais"),
        Classification("20.19-3", "Fabricação de produtos químicos inorgânicos não especificados anteriormente"),
        Classification("20.2", "Fabricação de produtos químicos orgânicos"),
        Classification("20.21-5", "Fabricação de produtos petroquímicos básicos"),
        Classification("20.22-3", "Fabricação de intermediários para plastificantes, resinas e fibras"),
        Classification("20.29-1", "Fabricação de produtos químicos orgânicos não especificados anteriormente"),
        Classification("20.3", "Fabricação de resinas e elastômeros"),
        Classification("20.31-2", "Fabricação de resinas termoplásticas"),
        Classification("20.32-1", "Fabricação de resinas termofixas"),
        Classification("20.33-9", "Fabricação de elastômeros"),
        Classification("20.4", "Fabricação de fibras artificiais e sintéticas"),
        Classification("20.40-1", "Fabricação de fibras artificiais e sintéticas"),
        Classification("20.5", "Fabricação de defensivos agrícolas e desinfestantes domissanitários"),
        Classification("20.51-7", "Fabricação de defensivos agrícolas"),
        Classification("20.52-5", "Fabricação de desinfestantes domissanitários"),
        Classification(
            "20.6",
            "Fabricação de sabões, detergentes, produtos de limpeza, cosméticos, produtos de perfumaria e de higiene pessoal",
        ),
        Classification("20.61-4", "Fabricação de sabões e detergentes sintéticos"),
        Classification("20.62-2", "Fabricação de produtos de limpeza e polimento"),
        Classification("20.63-1", "Fabricação de cosméticos, produtos de perfumaria e de higiene pessoal"),
        Classification("20.7", "Fabricação de tintas, vernizes, esmaltes, lacas e produtos afins"),
        Classification("20.71-1", "Fabricação de tintas, vernizes, esmaltes e lacas"),
        Classification("20.72-0", "Fabricação de tintas de impressão"),
        Classification("20.73-8", "Fabricação de impermeabilizantes, solventes e produtos afins"),
        Classification("20.9", "Fabricação de produtos e preparados químicos diversos"),
        Classification("20.91-6", "Fabricação de adesivos e selantes"),
        Classification("20.92-4", "Fabricação de explosivos"),
        Classification("20.93-2", "Fabricação de aditivos de uso industrial"),
        Classification("20.94-1", "Fabricação de catalisadores"),
        Classification("20.99-1", "Fabricação de produtos químicos não especificados anteriormente"),
        Classification("21", "FABRICAÇÃO DE PRODUTOS FARMOQUÍMICOS E FARMACÊUTICOS"),
        Classification("21.1", "Fabricação de produtos farmoquímicos"),
        Classification("21.10-6", "Fabricação de produtos farmoquímicos"),
        Classification("21.2", "Fabricação de produtos farmacêuticos"),
        Classification("21.21-1", "Fabricação de medicamentos para uso humano"),
        Classification("21.22-0", "Fabricação de medicamentos para uso veterinário"),
        Classification("21.23-8", "Fabricação de preparações farmacêuticas"),
        Classification("22", "FABRICAÇÃO DE PRODUTOS DE BORRACHA E DE MATERIAL PLÁSTICO"),
        Classification("22.1", "Fabricação de produtos de borracha"),
        Classification("22.11-1", "Fabricação de pneumáticos e de câmaras-de-ar"),
        Classification("22.12-9", "Reforma de pneumáticos usados"),
        Classification("22.19-6", "Fabricação de artefatos de borracha não especificados anteriormente"),
        Classification("22.2", "Fabricação de produtos de material plástico"),
        Classification("22.21-8", "Fabricação de laminados planos e tubulares de material plástico"),
        Classification("22.22-6", "Fabricação de embalagens de material plástico"),
        Classification("22.23-4", "Fabricação de tubos e acessórios de material plástico para uso na construção"),
        Classification("22.29-3", "Fabricação de artefatos de material plástico não especificados anteriormente"),
        Classification("23", "FABRICAÇÃO DE PRODUTOS DE MINERAIS NÃO-METÁLICOS"),
        Classification("23.1", "Fabricação de vidro e de produtos do vidro"),
        Classification("23.11-7", "Fabricação de vidro plano e de segurança"),
        Classification("23.12-5", "Fabricação de embalagens de vidro"),
        Classification("23.19-2", "Fabricação de artigos de vidro"),
        Classification("23.2", "Fabricação de cimento"),
        Classification("23.20-6", "Fabricação de cimento"),
        Classification(
            "23.3", "Fabricação de artefatos de concreto, cimento, fibrocimento, gesso e materiais semelhantes"
        ),
        Classification(
            "23.30-3", "Fabricação de artefatos de concreto, cimento, fibrocimento, gesso e materiais semelhantes"
        ),
        Classification("23.4", "Fabricação de produtos cerâmicos"),
        Classification("23.41-9", "Fabricação de produtos cerâmicos refratários"),
        Classification("23.42-7", "Fabricação de produtos cerâmicos não-refratários para uso estrutural na construção"),
        Classification("23.49-4", "Fabricação de produtos cerâmicos não-refratários não especificados anteriormente"),
        Classification("23.9", "Aparelhamento de pedras e fabricação de outros produtos de minerais não-metálicos"),
        Classification("23.91-5", "Aparelhamento e outros trabalhos em pedras"),
        Classification("23.92-3", "Fabricação de cal e gesso"),
        Classification("23.99-1", "Fabricação de produtos de minerais não-metálicos não especificados anteriormente"),
        Classification("24", "METALURGIA"),
        Classification("24.1", "Produção de ferro-gusa e de ferroligas"),
        Classification("24.11-3", "Produção de ferro-gusa"),
        Classification("24.12-1", "Produção de ferroligas"),
        Classification("24.2", "Siderurgia"),
        Classification("24.21-1", "Produção de semi-acabados de aço"),
        Classification("24.22-9", "Produção de laminados planos de aço"),
        Classification("24.23-7", "Produção de laminados longos de aço"),
        Classification("24.24-5", "Produção de relaminados, trefilados e perfilados de aço"),
        Classification("24.3", "Produção de tubos de aço, exceto tubos sem costura"),
        Classification("24.31-8", "Produção de tubos de aço com costura"),
        Classification("24.39-3", "Produção de outros tubos de ferro e aço"),
        Classification("24.4", "Metalurgia dos metais não-ferrosos"),
        Classification("24.41-5", "Metalurgia do alumínio e suas ligas"),
        Classification("24.42-3", "Metalurgia dos metais preciosos"),
        Classification("24.43-1", "Metalurgia do cobre"),
        Classification("24.49-1", "Metalurgia dos metais não-ferrosos e suas ligas não especificados anteriormente"),
        Classification("24.5", "Fundição"),
        Classification("24.51-2", "Fundição de ferro e aço"),
        Classification("24.52-1", "Fundição de metais não-ferrosos e suas ligas"),
        Classification("25", "FABRICAÇÃO DE PRODUTOS DE METAL, EXCETO MÁQUINAS E EQUIPAMENTOS"),
        Classification("25.1", "Fabricação de estruturas metálicas e obras de caldeiraria pesada"),
        Classification("25.11-0", "Fabricação de estruturas metálicas"),
        Classification("25.12-8", "Fabricação de esquadrias de metal"),
        Classification("25.13-6", "Fabricação de obras de caldeiraria pesada"),
        Classification("25.2", "Fabricação de tanques, reservatórios metálicos e caldeiras"),
        Classification(
            "25.21-7", "Fabricação de tanques, reservatórios metálicos e caldeiras para aquecimento central"
        ),
        Classification(
            "25.22-5", "Fabricação de caldeiras geradoras de vapor, exceto para aquecimento central e para veículos"
        ),
        Classification("25.3", "Forjaria, estamparia, metalurgia do pó e serviços de tratamento de metais"),
        Classification("25.31-4", "Produção de forjados de aço e de metais não-ferrosos e suas ligas"),
        Classification("25.32-2", "Produção de artefatos estampados de metal; metalurgia do pó"),
        Classification("25.39-0", "Serviços de usinagem, solda, tratamento e revestimento em metais"),
        Classification("25.4", "Fabricação de artigos de cutelaria, de serralheria e ferramentas"),
        Classification("25.41-1", "Fabricação de artigos de cutelaria"),
        Classification("25.42-0", "Fabricação de artigos de serralheria, exceto esquadrias"),
        Classification("25.43-8", "Fabricação de ferramentas"),
        Classification("25.5", "Fabricação de equipamento bélico pesado, armas e munições"),
        Classification("25.50-1", "Fabricação de equipamento bélico pesado, armas e munições"),
        Classification("25.9", "Fabricação de produtos de metal não especificados anteriormente"),
        Classification("25.91-8", "Fabricação de embalagens metálicas"),
        Classification("25.92-6", "Fabricação de produtos de trefilados de metal"),
        Classification("25.93-4", "Fabricação de artigos de metal para uso doméstico e pessoal"),
        Classification("25.99-3", "Fabricação de produtos de metal não especificados anteriormente"),
        Classification("26", "FABRICAÇÃO DE EQUIPAMENTOS DE INFORMÁTICA, PRODUTOS ELETRÔNICOS E ÓPTICOS"),
        Classification("26.1", "Fabricação de componentes eletrônicos"),
        Classification("26.10-8", "Fabricação de componentes eletrônicos"),
        Classification("26.2", "Fabricação de equipamentos de informática e periféricos"),
        Classification("26.21-3", "Fabricação de equipamentos de informática"),
        Classification("26.22-1", "Fabricação de periféricos para equipamentos de informática"),
        Classification("26.3", "Fabricação de equipamentos de comunicação"),
        Classification("26.31-1", "Fabricação de equipamentos transmissores de comunicação"),
        Classification("26.32-9", "Fabricação de aparelhos telefônicos e de outros equipamentos de comunicação"),
        Classification(
            "26.4", "Fabricação de aparelhos de recepção, reprodução, gravação e amplificação de áudio e vídeo"
        ),
        Classification(
            "26.40-0", "Fabricação de aparelhos de recepção, reprodução, gravação e amplificação de áudio e vídeo"
        ),
        Classification(
            "26.5", "Fabricação de aparelhos e instrumentos de medida, teste e controle; cronômetros e relógios"
        ),
        Classification("26.51-5", "Fabricação de aparelhos e equipamentos de medida, teste e controle"),
        Classification("26.52-3", "Fabricação de cronômetros e relógios"),
        Classification(
            "26.6", "Fabricação de aparelhos eletromédicos e eletroterapêuticos e equipamentos de irradiação"
        ),
        Classification(
            "26.60-4", "Fabricação de aparelhos eletromédicos e eletroterapêuticos e equipamentos de irradiação"
        ),
        Classification("26.7", "Fabricação de equipamentos e instrumentos ópticos, fotográficos e cinematográficos"),
        Classification("26.70-1", "Fabricação de equipamentos e instrumentos ópticos, fotográficos e cinematográficos"),
        Classification("26.8", "Fabricação de mídias virgens, magnéticas e ópticas"),
        Classification("26.80-9", "Fabricação de mídias virgens, magnéticas e ópticas"),
        Classification("27", "FABRICAÇÃO DE MÁQUINAS, APARELHOS E MATERIAIS ELÉTRICOS"),
        Classification("27.1", "Fabricação de geradores, transformadores e motores elétricos"),
        Classification("27.10-4", "Fabricação de geradores, transformadores e motores elétricos"),
        Classification("27.2", "Fabricação de pilhas, baterias e acumuladores elétricos"),
        Classification(
            "27.21-0", "Fabricação de pilhas, baterias e acumuladores elétricos, exceto para veículos automotores"
        ),
        Classification("27.22-8", "Fabricação de baterias e acumuladores para veículos automotores"),
        Classification("27.3", "Fabricação de equipamentos para distribuição e controle de energia elétrica"),
        Classification(
            "27.31-7", "Fabricação de aparelhos e equipamentos para distribuição e controle de energia elétrica"
        ),
        Classification("27.32-5", "Fabricação de material elétrico para instalações em circuito de consumo"),
        Classification("27.33-3", "Fabricação de fios, cabos e condutores elétricos isolados"),
        Classification("27.4", "Fabricação de lâmpadas e outros equipamentos de iluminação"),
        Classification("27.40-6", "Fabricação de lâmpadas e outros equipamentos de iluminação"),
        Classification("27.5", "Fabricação de eletrodomésticos"),
        Classification(
            "27.51-1", "Fabricação de fogões, refrigeradores e máquinas de lavar e secar para uso doméstico"
        ),
        Classification("27.59-7", "Fabricação de aparelhos eletrodomésticos não especificados anteriormente"),
        Classification("27.9", "Fabricação de equipamentos e aparelhos elétricos não especificados anteriormente"),
        Classification("27.90-2", "Fabricação de equipamentos e aparelhos elétricos não especificados anteriormente"),
        Classification("28", "FABRICAÇÃO DE MÁQUINAS E EQUIPAMENTOS"),
        Classification("28.1", "Fabricação de motores, bombas, compressores e equipamentos de transmissão"),
        Classification("28.11-9", "Fabricação de motores e turbinas, exceto para aviões e veículos rodoviários"),
        Classification("28.12-7", "Fabricação de equipamentos hidráulicos e pneumáticos, exceto válvulas"),
        Classification("28.13-5", "Fabricação de válvulas, registros e dispositivos semelhantes"),
        Classification("28.14-3", "Fabricação de compressores"),
        Classification("28.15-1", "Fabricação de equipamentos de transmissão para fins industriais"),
        Classification("28.2", "Fabricação de máquinas e equipamentos de uso geral"),
        Classification("28.21-6", "Fabricação de aparelhos e equipamentos para instalações térmicas"),
        Classification(
            "28.22-4", "Fabricação de máquinas, equipamentos e aparelhos para transporte e elevação de cargas e pessoas"
        ),
        Classification(
            "28.23-2", "Fabricação de máquinas e aparelhos de refrigeração e ventilação para uso industrial e comercial"
        ),
        Classification("28.24-1", "Fabricação de aparelhos e equipamentos de ar condicionado"),
        Classification("28.25-9", "Fabricação de máquinas e equipamentos para saneamento básico e ambiental"),
        Classification("28.29-1", "Fabricação de máquinas e equipamentos de uso geral não especificados anteriormente"),
        Classification("28.3", "Fabricação de tratores e de máquinas e equipamentos para a agricultura e pecuária"),
        Classification("28.31-3", "Fabricação de tratores agrícolas"),
        Classification("28.32-1", "Fabricação de equipamentos para irrigação agrícola"),
        Classification(
            "28.33-0", "Fabricação de máquinas e equipamentos para a agricultura e pecuária, exceto para irrigação"
        ),
        Classification("28.4", "Fabricação de máquinas-ferramenta"),
        Classification("28.40-2", "Fabricação de máquinas-ferramenta"),
        Classification("28.5", "Fabricação de máquinas e equipamentos de uso na extração mineral e na construção"),
        Classification("28.51-8", "Fabricação de máquinas e equipamentos para a prospecção e extração de petróleo"),
        Classification(
            "28.52-6",
            "Fabricação de outras máquinas e equipamentos para uso na extração mineral, exceto na extração de petróleo",
        ),
        Classification("28.53-4", "Fabricação de tratores, exceto agrícolas"),
        Classification(
            "28.54-2",
            "Fabricação de máquinas e equipamentos para terraplenagem, pavimentação e construção, exceto tratores",
        ),
        Classification("28.6", "Fabricação de máquinas e equipamentos de uso industrial específico"),
        Classification("28.61-5", "Fabricação de máquinas para a indústria metalúrgica, exceto máquinas-ferramenta"),
        Classification(
            "28.62-3", "Fabricação de máquinas e equipamentos para as indústrias de alimentos, bebidas e fumo"
        ),
        Classification("28.63-1", "Fabricação de máquinas e equipamentos para a indústria têxtil"),
        Classification(
            "28.64-0", "Fabricação de máquinas e equipamentos para as indústrias do vestuário, do couro e de calçados"
        ),
        Classification(
            "28.65-8",
            "Fabricação de máquinas e equipamentos para as indústrias de celulose, papel e papelão e artefatos",
        ),
        Classification("28.66-6", "Fabricação de máquinas e equipamentos para a indústria do plástico"),
        Classification(
            "28.69-1",
            "Fabricação de máquinas e equipamentos para uso industrial específico não especificados anteriormente",
        ),
        Classification("29", "FABRICAÇÃO DE VEÍCULOS AUTOMOTORES, REBOQUES E CARROCERIAS"),
        Classification("29.1", "Fabricação de automóveis, camionetas e utilitários"),
        Classification("29.10-7", "Fabricação de automóveis, camionetas e utilitários"),
        Classification("29.2", "Fabricação de caminhões e ônibus"),
        Classification("29.20-4", "Fabricação de caminhões e ônibus"),
        Classification("29.3", "Fabricação de cabines, carrocerias e reboques para veículos automotores"),
        Classification("29.30-1", "Fabricação de cabines, carrocerias e reboques para veículos automotores"),
        Classification("29.4", "Fabricação de peças e acessórios para veículos automotores"),
        Classification("29.41-7", "Fabricação de peças e acessórios para o sistema motor de veículos automotores"),
        Classification(
            "29.42-5",
            "Fabricação de peças e acessórios para os sistemas de marcha e transmissão de veículos automotores",
        ),
        Classification("29.43-3", "Fabricação de peças e acessórios para o sistema de freios de veículos automotores"),
        Classification(
            "29.44-1", "Fabricação de peças e acessórios para o sistema de direção e suspensão de veículos automotores"
        ),
        Classification(
            "29.45-0", "Fabricação de material elétrico e eletrônico para veículos automotores, exceto baterias"
        ),
        Classification(
            "29.49-2", "Fabricação de peças e acessórios para veículos automotores não especificados anteriormente"
        ),
        Classification("29.5", "Recondicionamento e recuperação de motores para veículos automotores"),
        Classification("29.50-6", "Recondicionamento e recuperação de motores para veículos automotores"),
        Classification("30", "FABRICAÇÃO DE OUTROS EQUIPAMENTOS DE TRANSPORTE, EXCETO VEÍCULOS AUTOMOTORES"),
        Classification("30.1", "Construção de embarcações"),
        Classification("30.11-3", "Construção de embarcações e estruturas flutuantes"),
        Classification("30.12-1", "Construção de embarcações para esporte e lazer"),
        Classification("30.3", "Fabricação de veículos ferroviários"),
        Classification("30.31-8", "Fabricação de locomotivas, vagões e outros materiais rodantes"),
        Classification("30.32-6", "Fabricação de peças e acessórios para veículos ferroviários"),
        Classification("30.4", "Fabricação de aeronaves"),
        Classification("30.41-5", "Fabricação de aeronaves"),
        Classification("30.42-3", "Fabricação de turbinas, motores e outros componentes e peças para aeronaves"),
        Classification("30.5", "Fabricação de veículos militares de combate"),
        Classification("30.50-4", "Fabricação de veículos militares de combate"),
        Classification("30.9", "Fabricação de equipamentos de transporte não especificados anteriormente"),
        Classification("30.91-1", "Fabricação de motocicletas"),
        Classification("30.92-0", "Fabricação de bicicletas e triciclos não-motorizados"),
        Classification("30.99-7", "Fabricação de equipamentos de transporte não especificados anteriormente"),
        Classification("31", "FABRICAÇÃO DE MÓVEIS"),
        Classification("31.0", "Fabricação de móveis"),
        Classification("31.01-2", "Fabricação de móveis com predominância de madeira"),
        Classification("31.02-1", "Fabricação de móveis com predominância de metal"),
        Classification("31.03-9", "Fabricação de móveis de outros materiais, exceto madeira e metal"),
        Classification("31.04-7", "Fabricação de colchões"),
        Classification("32", "FABRICAÇÃO DE PRODUTOS DIVERSOS"),
        Classification("32.1", "Fabricação de artigos de joalheria, bijuteria e semelhantes"),
        Classification("32.11-6", "Lapidação de gemas e fabricação de artefatos de ourivesaria e joalheria"),
        Classification("32.12-4", "Fabricação de bijuterias e artefatos semelhantes"),
        Classification("32.2", "Fabricação de instrumentos musicais"),
        Classification("32.20-5", "Fabricação de instrumentos musicais"),
        Classification("32.3", "Fabricação de artefatos para pesca e esporte"),
        Classification("32.30-2", "Fabricação de artefatos para pesca e esporte"),
        Classification("32.4", "Fabricação de brinquedos e jogos recreativos"),
        Classification("32.40-0", "Fabricação de brinquedos e jogos recreativos"),
        Classification(
            "32.5", "Fabricação de instrumentos e materiais para uso médico e odontológico e de artigos ópticos"
        ),
        Classification(
            "32.50-7", "Fabricação de instrumentos e materiais para uso médico e odontológico e de artigos ópticos"
        ),
        Classification("32.9", "Fabricação de produtos diversos"),
        Classification("32.91-4", "Fabricação de escovas, pincéis e vassouras"),
        Classification(
            "32.92-2", "Fabricação de equipamentos e acessórios para segurança e proteção pessoal e profissional"
        ),
        Classification("32.99-0", "Fabricação de produtos diversos não especificados anteriormente"),
        Classification("33", "MANUTENÇÃO, REPARAÇÃO E INSTALAÇÃO DE MÁQUINAS E EQUIPAMENTOS"),
        Classification("33.1", "Manutenção e reparação de máquinas e equipamentos"),
        Classification(
            "33.11-2", "Manutenção e reparação de tanques, reservatórios metálicos e caldeiras, exceto para veículos"
        ),
        Classification("33.12-1", "Manutenção e reparação de equipamentos eletrônicos e ópticos"),
        Classification("33.13-9", "Manutenção e reparação de máquinas e equipamentos elétricos"),
        Classification("33.14-7", "Manutenção e reparação de máquinas e equipamentos da indústria mecânica"),
        Classification("33.15-5", "Manutenção e reparação de veículos ferroviários"),
        Classification("33.16-3", "Manutenção e reparação de aeronaves"),
        Classification("33.17-1", "Manutenção e reparação de embarcações"),
        Classification("33.19-8", "Manutenção e reparação de equipamentos e produtos não especificados anteriormente"),
        Classification("33.2", "Instalação de máquinas e equipamentos"),
        Classification("33.21-0", "Instalação de máquinas e equipamentos industriais"),
        Classification("33.29-5", "Instalação de equipamentos não especificados anteriormente"),
        Classification("D", "ELETRICIDADE E GÁS"),
        Classification("35", "ELETRICIDADE, GÁS E OUTRAS UTILIDADES"),
        Classification("35.1", "Geração, transmissão e distribuição de energia elétrica"),
        Classification("35.11-5", "Geração de energia elétrica"),
        Classification("35.12-3", "Transmissão de energia elétrica"),
        Classification("35.13-1", "Comércio atacadista de energia elétrica"),
        Classification("35.14-0", "Distribuição de energia elétrica"),
        Classification("35.2", "Produção e distribuição de combustíveis gasosos por redes urbanas"),
        Classification(
            "35.20-4",
            "Produção de gás; processamento de gás natural; distribuição de combustíveis gasosos por redes urbanas",
        ),
        Classification("35.3", "Produção e distribuição de vapor, água quente e ar condicionado"),
        Classification("35.30-1", "Produção e distribuição de vapor, água quente e ar condicionado"),
        Classification("E", "ÁGUA, ESGOTO, ATIVIDADES DE GESTÃO DE RESÍDUOS E DESCONTAMINAÇÃO"),
        Classification("36", "CAPTAÇÃO, TRATAMENTO E DISTRIBUIÇÃO DE ÁGUA"),
        Classification("36.0", "Captação, tratamento e distribuição de água"),
        Classification("36.00-6", "Captação, tratamento e distribuição de água"),
        Classification("37", "ESGOTO E ATIVIDADES RELACIONADAS"),
        Classification("37.0", "Esgoto e atividades relacionadas"),
        Classification("37.01-1", "Gestão de redes de esgoto"),
        Classification("37.02-9", "Atividades relacionadas a esgoto, exceto a gestão de redes"),
        Classification("38", "COLETA, TRATAMENTO E DISPOSIÇÃO DE RESÍDUOS; RECUPERAÇÃO DE MATERIAIS"),
        Classification("38.1", "Coleta de resíduos"),
        Classification("38.11-4", "Coleta de resíduos não-perigosos"),
        Classification("38.12-2", "Coleta de resíduos perigosos"),
        Classification("38.2", "Tratamento e disposição de resíduos"),
        Classification("38.21-1", "Tratamento e disposição de resíduos não-perigosos"),
        Classification("38.22-0", "Tratamento e disposição de resíduos perigosos"),
        Classification("38.3", "Recuperação de materiais"),
        Classification("38.31-9", "Recuperação de materiais metálicos"),
        Classification("38.32-7", "Recuperação de materiais plásticos"),
        Classification("38.39-4", "Recuperação de materiais não especificados anteriormente"),
        Classification("39", "DESCONTAMINAÇÃO E OUTROS SERVIÇOS DE GESTÃO DE RESÍDUOS"),
        Classification("39.0", "Descontaminação e outros serviços de gestão de resíduos"),
        Classification("39.00-5", "Descontaminação e outros serviços de gestão de resíduos"),
        Classification("F", "CONSTRUÇÃO"),
        Classification("41", "CONSTRUÇÃO DE EDIFÍCIOS"),
        Classification("41.1", "Incorporação de empreendimentos imobiliários"),
        Classification("41.10-7", "Incorporação de empreendimentos imobiliários"),
        Classification("41.2", "Construção de edifícios"),
        Classification("41.20-4", "Construção de edifícios"),
        Classification("42", "OBRAS DE INFRA-ESTRUTURA"),
        Classification("42.1", "Construção de rodovias, ferrovias, obras urbanas e obras-de-arte especiais"),
        Classification("42.11-1", "Construção de rodovias e ferrovias"),
        Classification("42.12-0", "Construção de obras-de-arte especiais"),
        Classification("42.13-8", "Obras de urbanização - ruas, praças e calçadas"),
        Classification(
            "42.2",
            "Obras de infra-estrutura para energia elétrica, telecomunicações, água, esgoto e transporte por dutos",
        ),
        Classification("42.21-9", "Obras para geração e distribuição de energia elétrica e para telecomunicações"),
        Classification(
            "42.22-7", "Construção de redes de abastecimento de água, coleta de esgoto e construções correlatas"
        ),
        Classification("42.23-5", "Construção de redes de transportes por dutos, exceto para água e esgoto"),
        Classification("42.9", "Construção de outras obras de infra-estrutura"),
        Classification("42.91-0", "Obras portuárias, marítimas e fluviais"),
        Classification("42.92-8", "Montagem de instalações industriais e de estruturas metálicas"),
        Classification("42.99-5", "Obras de engenharia civil não especificadas anteriormente"),
        Classification("43", "SERVIÇOS ESPECIALIZADOS PARA CONSTRUÇÃO"),
        Classification("43.1", "Demolição e preparação do terreno"),
        Classification("43.11-8", "Demolição e preparação de canteiros de obras"),
        Classification("43.12-6", "Perfurações e sondagens"),
        Classification("43.13-4", "Obras de terraplenagem"),
        Classification("43.19-3", "Serviços de preparação do terreno não especificados anteriormente"),
        Classification("43.2", "Instalações elétricas, hidráulicas e outras instalações em construções"),
        Classification("43.21-5", "Instalações elétricas"),
        Classification("43.22-3", "Instalações hidráulicas, de sistemas de ventilação e refrigeração"),
        Classification("43.29-1", "Obras de instalações em construções não especificadas anteriormente"),
        Classification("43.3", "Obras de acabamento"),
        Classification("43.30-4", "Obras de acabamento"),
        Classification("43.9", "Outros serviços especializados para construção"),
        Classification("43.91-6", "Obras de fundações"),
        Classification("43.99-1", "Serviços especializados para construção não especificados anteriormente"),
        Classification("G", "COMÉRCIO; REPARAÇÃO DE VEÍCULOS AUTOMOTORES E MOTOCICLETAS"),
        Classification("45", "COMÉRCIO E REPARAÇÃO DE VEÍCULOS AUTOMOTORES E MOTOCICLETAS"),
        Classification("45.1", "Comércio de veículos automotores"),
        Classification("45.11-1", "Comércio a varejo e por atacado de veículos automotores"),
        Classification("45.12-9", "Representantes comerciais e agentes do comércio de veículos automotores"),
        Classification("45.2", "Manutenção e reparação de veículos automotores"),
        Classification("45.20-0", "Manutenção e reparação de veículos automotores"),
        Classification("45.3", "Comércio de peças e acessórios para veículos automotores"),
        Classification("45.30-7", "Comércio de peças e acessórios para veículos automotores"),
        Classification("45.4", "Comércio, manutenção e reparação de motocicletas, peças e acessórios"),
        Classification("45.41-2", "Comércio por atacado e a varejo de motocicletas, peças e acessórios"),
        Classification(
            "45.42-1", "Representantes comerciais e agentes do comércio de motocicletas, peças e acessórios"
        ),
        Classification("45.43-9", "Manutenção e reparação de motocicletas"),
        Classification("46", "COMÉRCIO POR ATACADO, EXCETO VEÍCULOS AUTOMOTORES E MOTOCICLETAS"),
        Classification(
            "46.1", "Representantes comerciais e agentes do comércio, exceto de veículos automotores e motocicletas"
        ),
        Classification(
            "46.11-7", "Representantes comerciais e agentes do comércio de matérias-primas agrícolas e animais vivos"
        ),
        Classification(
            "46.12-5",
            "Representantes comerciais e agentes do comércio de combustíveis, minerais, produtos siderúrgicos e químicos",
        ),
        Classification(
            "46.13-3", "Representantes comerciais e agentes do comércio de madeira, material de construção e ferragens"
        ),
        Classification(
            "46.14-1",
            "Representantes comerciais e agentes do comércio de máquinas, equipamentos, embarcações e aeronaves",
        ),
        Classification(
            "46.15-0",
            "Representantes comerciais e agentes do comércio de eletrodomésticos, móveis e artigos de uso doméstico",
        ),
        Classification(
            "46.16-8",
            "Representantes comerciais e agentes do comércio de têxteis, vestuário, calçados e artigos de viagem",
        ),
        Classification(
            "46.17-6", "Representantes comerciais e agentes do comércio de produtos alimentícios, bebidas e fumo"
        ),
        Classification(
            "46.18-4",
            "Representantes comerciais e agentes do comércio especializado em produtos não especificados anteriormente",
        ),
        Classification(
            "46.19-2", "Representantes comerciais e agentes do comércio de mercadorias em geral não especializado"
        ),
        Classification("46.2", "Comércio atacadista de matérias-primas agrícolas e animais vivos"),
        Classification("46.21-4", "Comércio atacadista de café em grão"),
        Classification("46.22-2", "Comércio atacadista de soja"),
        Classification(
            "46.23-1",
            "Comércio atacadista de animais vivos, alimentos para animais e matérias-primas agrícolas, exceto café e soja",
        ),
        Classification("46.3", "Comércio atacadista especializado em produtos alimentícios, bebidas e fumo"),
        Classification("46.31-1", "Comércio atacadista de leite e laticínios"),
        Classification(
            "46.32-0", "Comércio atacadista de cereais e leguminosas beneficiados, farinhas, amidos e féculas"
        ),
        Classification("46.33-8", "Comércio atacadista de hortifrutigranjeiros"),
        Classification("46.34-6", "Comércio atacadista de carnes, produtos da carne e pescado"),
        Classification("46.35-4", "Comércio atacadista de bebidas"),
        Classification("46.36-2", "Comércio atacadista de produtos do fumo"),
        Classification(
            "46.37-1", "Comércio atacadista especializado em produtos alimentícios não especificados anteriormente"
        ),
        Classification("46.39-7", "Comércio atacadista de produtos alimentícios em geral"),
        Classification("46.4", "Comércio atacadista de produtos de consumo não-alimentar"),
        Classification("46.41-9", "Comércio atacadista de tecidos, artefatos de tecidos e de armarinho"),
        Classification("46.42-7", "Comércio atacadista de artigos do vestuário e acessórios"),
        Classification("46.43-5", "Comércio atacadista de calçados e artigos de viagem"),
        Classification("46.44-3", "Comércio atacadista de produtos farmacêuticos para uso humano e veterinário"),
        Classification(
            "46.45-1",
            "Comércio atacadista de instrumentos e materiais para uso médico, cirúrgico, ortopédico e odontológico",
        ),
        Classification("46.46-0", "Comércio atacadista de cosméticos, produtos de perfumaria e de higiene pessoal"),
        Classification(
            "46.47-8",
            "Comércio atacadista de artigos de escritório e de papelaria; livros, jornais e outras publicações",
        ),
        Classification(
            "46.49-4",
            "Comércio atacadista de equipamentos e artigos de uso pessoal e doméstico não especificados anteriormente",
        ),
        Classification(
            "46.5", "Comércio atacadista de equipamentos e produtos de tecnologias de informação e comunicação"
        ),
        Classification("46.51-6", "Comércio atacadista de computadores, periféricos e suprimentos de informática"),
        Classification(
            "46.52-4", "Comércio atacadista de componentes eletrônicos e equipamentos de telefonia e comunicação"
        ),
        Classification(
            "46.6",
            "Comércio atacadista de máquinas, aparelhos e equipamentos, exceto de tecnologias de informação e comunicação",
        ),
        Classification(
            "46.61-3", "Comércio atacadista de máquinas, aparelhos e equipamentos para uso agropecuário; partes e peças"
        ),
        Classification(
            "46.62-1",
            "Comércio atacadista de máquinas, equipamentos para terraplenagem, mineração e construção; partes e peças",
        ),
        Classification("46.63-0", "Comércio atacadista de máquinas e equipamentos para uso industrial; partes e peças"),
        Classification(
            "46.64-8",
            "Comércio atacadista de máquinas, aparelhos e equipamentos para uso odonto-médico-hospitalar; partes e peças",
        ),
        Classification("46.65-6", "Comércio atacadista de máquinas e equipamentos para uso comercial; partes e peças"),
        Classification(
            "46.69-9",
            "Comércio atacadista de máquinas, aparelhos e equipamentos não especificados anteriormente; partes e peças",
        ),
        Classification(
            "46.7", "Comércio atacadista de madeira, ferragens, ferramentas, material elétrico e material de construção"
        ),
        Classification("46.71-1", "Comércio atacadista de madeira e produtos derivados"),
        Classification("46.72-9", "Comércio atacadista de ferragens e ferramentas"),
        Classification("46.73-7", "Comércio atacadista de material elétrico"),
        Classification("46.74-5", "Comércio atacadista de cimento"),
        Classification(
            "46.79-6",
            "Comércio atacadista especializado de materiais de construção não especificados anteriormente e de materiais de construção em geral",
        ),
        Classification("46.8", "Comércio atacadista especializado em outros produtos"),
        Classification(
            "46.81-8", "Comércio atacadista de combustíveis sólidos, líquidos e gasosos, exceto gás natural e GLP"
        ),
        Classification("46.82-6", "Comércio atacadista de gás liqüefeito de petróleo (GLP)"),
        Classification(
            "46.83-4", "Comércio atacadista de defensivos agrícolas, adubos, fertilizantes e corretivos do solo"
        ),
        Classification("46.84-2", "Comércio atacadista de produtos químicos e petroquímicos, exceto agroquímicos"),
        Classification(
            "46.85-1", "Comércio atacadista de produtos siderúrgicos e metalúrgicos, exceto para construção"
        ),
        Classification("46.86-9", "Comércio atacadista de papel e papelão em bruto e de embalagens"),
        Classification("46.87-7", "Comércio atacadista de resíduos e sucatas"),
        Classification(
            "46.89-3",
            "Comércio atacadista especializado de outros produtos intermediários não especificados anteriormente",
        ),
        Classification("46.9", "Comércio atacadista não-especializado"),
        Classification(
            "46.91-5", "Comércio atacadista de mercadorias em geral, com predominância de produtos alimentícios"
        ),
        Classification(
            "46.92-3", "Comércio atacadista de mercadorias em geral, com predominância de insumos agropecuários"
        ),
        Classification(
            "46.93-1",
            "Comércio atacadista de mercadorias em geral, sem predominância de alimentos ou de insumos agropecuários",
        ),
        Classification("47", "COMÉRCIO VAREJISTA"),
        Classification("47.1", "Comércio varejista não-especializado"),
        Classification(
            "47.11-3",
            "Comércio varejista de mercadorias em geral, com predominância de produtos alimentícios - hipermercados e supermercados",
        ),
        Classification(
            "47.12-1",
            "Comércio varejista de mercadorias em geral, com predominância de produtos alimentícios - minimercados, mercearias e armazéns",
        ),
        Classification(
            "47.13-0", "Comércio varejista de mercadorias em geral, sem predominância de produtos alimentícios"
        ),
        Classification("47.2", "Comércio varejista de produtos alimentícios, bebidas e fumo"),
        Classification("47.21-1", "Comércio varejista de produtos de padaria, laticínio, doces, balas e semelhantes"),
        Classification("47.22-9", "Comércio varejista de carnes e pescados - açougues e peixarias"),
        Classification("47.23-7", "Comércio varejista de bebidas"),
        Classification("47.24-5", "Comércio varejista de hortifrutigranjeiros"),
        Classification(
            "47.29-6",
            "Comércio varejista de produtos alimentícios em geral ou especializado em produtos alimentícios não especificados anteriormente; produtos do fumo",
        ),
        Classification("47.3", "Comércio varejista de combustíveis para veículos automotores"),
        Classification("47.31-8", "Comércio varejista de combustíveis para veículos automotores"),
        Classification("47.32-6", "Comércio varejista de lubrificantes"),
        Classification("47.4", "Comércio varejista de material de construção"),
        Classification("47.41-5", "Comércio varejista de tintas e materiais para pintura"),
        Classification("47.42-3", "Comércio varejista de material elétrico"),
        Classification("47.43-1", "Comércio varejista de vidros"),
        Classification("47.44-0", "Comércio varejista de ferragens, madeira e materiais de construção"),
        Classification(
            "47.5",
            "Comércio varejista de equipamentos de informática e comunicação; equipamentos e artigos de uso doméstico",
        ),
        Classification("47.51-2", "Comércio varejista especializado de equipamentos e suprimentos de informática"),
        Classification("47.52-1", "Comércio varejista especializado de equipamentos de telefonia e comunicação"),
        Classification(
            "47.53-9", "Comércio varejista especializado de eletrodomésticos e equipamentos de áudio e vídeo"
        ),
        Classification("47.54-7", "Comércio varejista especializado de móveis, colchoaria e artigos de iluminação"),
        Classification("47.55-5", "Comércio varejista especializado de tecidos e artigos de cama, mesa e banho"),
        Classification("47.56-3", "Comércio varejista especializado de instrumentos musicais e acessórios"),
        Classification(
            "47.57-1",
            "Comércio varejista especializado de peças e acessórios para aparelhos eletroeletrônicos para uso doméstico, exceto informática e comunicação",
        ),
        Classification("47.59-8", "Comércio varejista de artigos de uso doméstico não especificados anteriormente"),
        Classification("47.6", "Comércio varejista de artigos culturais, recreativos e esportivos"),
        Classification("47.61-0", "Comércio varejista de livros, jornais, revistas e papelaria"),
        Classification("47.62-8", "Comércio varejista de discos, CDs, DVDs e fitas"),
        Classification("47.63-6", "Comércio varejista de artigos recreativos e esportivos"),
        Classification(
            "47.7",
            "Comércio varejista de produtos farmacêuticos, perfumaria e cosméticos e artigos médicos, ópticos e ortopédicos",
        ),
        Classification("47.71-7", "Comércio varejista de produtos farmacêuticos para uso humano e veterinário"),
        Classification("47.72-5", "Comércio varejista de cosméticos, produtos de perfumaria e de higiene pessoal"),
        Classification("47.73-3", "Comércio varejista de artigos médicos e ortopédicos"),
        Classification("47.74-1", "Comércio varejista de artigos de óptica"),
        Classification(
            "47.8", "Comércio varejista de produtos novos não especificados anteriormente e de produtos usados"
        ),
        Classification("47.81-4", "Comércio varejista de artigos do vestuário e acessórios"),
        Classification("47.82-2", "Comércio varejista de calçados e artigos de viagem"),
        Classification("47.83-1", "Comércio varejista de jóias e relógios"),
        Classification("47.84-9", "Comércio varejista de gás liqüefeito de petróleo (GLP)"),
        Classification("47.85-7", "Comércio varejista de artigos usados"),
        Classification("47.89-0", "Comércio varejista de outros produtos novos não especificados anteriormente"),
        Classification("47.9", "Comércio ambulante e outros tipos de comércio varejista"),
        Classification("47.90-3", "Comércio ambulante e outros tipos de comércio varejista"),
        Classification("H", "TRANSPORTE, ARMAZENAGEM E CORREIO"),
        Classification("49", "TRANSPORTE TERRESTRE"),
        Classification("49.1", "Transporte ferroviário e metroferroviário"),
        Classification("49.11-6", "Transporte ferroviário de carga"),
        Classification("49.12-4", "Transporte metroferroviário de passageiros"),
        Classification("49.2", "Transporte rodoviário de passageiros"),
        Classification(
            "49.21-3",
            "Transporte rodoviário coletivo de passageiros, com itinerário fixo, municipal e em região metropolitana",
        ),
        Classification(
            "49.22-1",
            "Transporte rodoviário coletivo de passageiros, com itinerário fixo, intermunicipal, interestadual e internacional",
        ),
        Classification("49.23-0", "Transporte rodoviário de táxi"),
        Classification("49.24-8", "Transporte escolar"),
        Classification(
            "49.29-9",
            "Transporte rodoviário coletivo de passageiros, sob regime de fretamento, e outros transportes rodoviários não especificados anteriormente",
        ),
        Classification("49.3", "Transporte rodoviário de carga"),
        Classification("49.30-2", "Transporte rodoviário de carga"),
        Classification("49.4", "Transporte dutoviário"),
        Classification("49.40-0", "Transporte dutoviário"),
        Classification("49.5", "Trens turísticos, teleféricos e similares"),
        Classification("49.50-7", "Trens turísticos, teleféricos e similares"),
        Classification("50", "TRANSPORTE AQUAVIÁRIO"),
        Classification("50.1", "Transporte marítimo de cabotagem e longo curso"),
        Classification("50.11-4", "Transporte marítimo de cabotagem"),
        Classification("50.12-2", "Transporte marítimo de longo curso"),
        Classification("50.2", "Transporte por navegação interior"),
        Classification("50.21-1", "Transporte por navegação interior de carga"),
        Classification("50.22-0", "Transporte por navegação interior de passageiros em linhas regulares"),
        Classification("50.3", "Navegação de apoio"),
        Classification("50.30-1", "Navegação de apoio"),
        Classification("50.9", "Outros transportes aquaviários"),
        Classification("50.91-2", "Transporte por navegação de travessia"),
        Classification("50.99-8", "Transportes aquaviários não especificados anteriormente"),
        Classification("51", "TRANSPORTE AÉREO"),
        Classification("51.1", "Transporte aéreo de passageiros"),
        Classification("51.11-1", "Transporte aéreo de passageiros regular"),
        Classification("51.12-9", "Transporte aéreo de passageiros não-regular"),
        Classification("51.2", "Transporte aéreo de carga"),
        Classification("51.20-0", "Transporte aéreo de carga"),
        Classification("51.3", "Transporte espacial"),
        Classification("51.30-7", "Transporte espacial"),
        Classification("52", "ARMAZENAMENTO E ATIVIDADES AUXILIARES DOS TRANSPORTES"),
        Classification("52.1", "Armazenamento, carga e descarga"),
        Classification("52.11-7", "Armazenamento"),
        Classification("52.12-5", "Carga e descarga"),
        Classification("52.2", "Atividades auxiliares dos transportes terrestres"),
        Classification("52.21-4", "Concessionárias de rodovias, pontes, túneis e serviços relacionados"),
        Classification("52.22-2", "Terminais rodoviários e ferroviários"),
        Classification("52.23-1", "Estacionamento de veículos"),
        Classification("52.29-0", "Atividades auxiliares dos transportes terrestres não especificadas anteriormente"),
        Classification("52.3", "Atividades auxiliares dos transportes aquaviários"),
        Classification("52.31-1", "Gestão de portos e terminais"),
        Classification("52.32-0", "Atividades de agenciamento marítimo"),
        Classification("52.39-7", "Atividades auxiliares dos transportes aquaviários não especificadas anteriormente"),
        Classification("52.4", "Atividades auxiliares dos transportes aéreos"),
        Classification("52.40-1", "Atividades auxiliares dos transportes aéreos"),
        Classification("52.5", "Atividades relacionadas à organização do transporte de carga"),
        Classification("52.50-8", "Atividades relacionadas à organização do transporte de carga"),
        Classification("53", "CORREIO E OUTRAS ATIVIDADES DE ENTREGA"),
        Classification("53.1", "Atividades de Correio"),
        Classification("53.10-5", "Atividades de Correio"),
        Classification("53.2", "Atividades de malote e de entrega"),
        Classification("53.20-2", "Atividades de malote e de entrega"),
        Classification("I", "ALOJAMENTO E ALIMENTAÇÃO"),
        Classification("55", "ALOJAMENTO"),
        Classification("55.1", "Hotéis e similares"),
        Classification("55.10-8", "Hotéis e similares"),
        Classification("55.9", "Outros tipos de alojamento não especificados anteriormente"),
        Classification("55.90-6", "Outros tipos de alojamento não especificados anteriormente"),
        Classification("56", "ALIMENTAÇÃO"),
        Classification("56.1", "Restaurantes e outros serviços de alimentação e bebidas"),
        Classification("56.11-2", "Restaurantes e outros estabelecimentos de serviços de alimentação e bebidas"),
        Classification("56.12-1", "Serviços ambulantes de alimentação"),
        Classification("56.2", "Serviços de catering, bufê e outros serviços de comida preparada"),
        Classification("56.20-1", "Serviços de catering, bufê e outros serviços de comida preparada"),
        Classification("J", "INFORMAÇÃO E COMUNICAÇÃO"),
        Classification("58", "EDIÇÃO E EDIÇÃO INTEGRADA À IMPRESSÃO"),
        Classification("58.1", "Edição de livros, jornais, revistas e outras atividades de edição"),
        Classification("58.11-5", "Edição de livros"),
        Classification("58.12-3", "Edição de jornais"),
        Classification("58.13-1", "Edição de revistas"),
        Classification("58.19-1", "Edição de cadastros, listas e outros produtos gráficos"),
        Classification("58.2", "Edição integrada à impressão de livros, jornais, revistas e outras publicações"),
        Classification("58.21-2", "Edição integrada à impressão de livros"),
        Classification("58.22-1", "Edição integrada à impressão de jornais"),
        Classification("58.23-9", "Edição integrada à impressão de revistas"),
        Classification("58.29-8", "Edição integrada à impressão de cadastros, listas e outros produtos gráficos"),
        Classification(
            "59",
            "ATIVIDADES CINEMATOGRÁFICAS, PRODUÇÃO DE VÍDEOS E DE PROGRAMAS DE TELEVISÃO; GRAVAÇÃO DE SOM E EDIÇÃO DE MÚSICA",
        ),
        Classification("59.1", "Atividades cinematográficas, produção de vídeos e de programas de televisão"),
        Classification("59.11-1", "Atividades de produção cinematográfica, de vídeos e de programas de televisão"),
        Classification("59.12-0", "Atividades de pós-produção cinematográfica, de vídeos e de programas de televisão"),
        Classification("59.13-8", "Distribuição cinematográfica, de vídeo e de programas de televisão"),
        Classification("59.14-6", "Atividades de exibição cinematográfica"),
        Classification("59.2", "Atividades de gravação de som e de edição de música"),
        Classification("59.20-1", "Atividades de gravação de som e de edição de música"),
        Classification("60", "ATIVIDADES DE RÁDIO E DE TELEVISÃO"),
        Classification("60.1", "Atividades de rádio"),
        Classification("60.10-1", "Atividades de rádio"),
        Classification("60.2", "Atividades de televisão"),
        Classification("60.21-7", "Atividades de televisão aberta"),
        Classification("60.22-5", "Programadoras e atividades relacionadas à televisão por assinatura"),
        Classification("61", "TELECOMUNICAÇÕES"),
        Classification("61.1", "Telecomunicações por fio"),
        Classification("61.10-8", "Telecomunicações por fio"),
        Classification("61.2", "Telecomunicações sem fio"),
        Classification("61.20-5", "Telecomunicações sem fio"),
        Classification("61.3", "Telecomunicações por satélite"),
        Classification("61.30-2", "Telecomunicações por satélite"),
        Classification("61.4", "Operadoras de televisão por assinatura"),
        Classification("61.41-8", "Operadoras de televisão por assinatura por cabo"),
        Classification("61.42-6", "Operadoras de televisão por assinatura por microondas"),
        Classification("61.43-4", "Operadoras de televisão por assinatura por satélite"),
        Classification("61.9", "Outras atividades de telecomunicações"),
        Classification("61.90-6", "Outras atividades de telecomunicações"),
        Classification("62", "ATIVIDADES DOS SERVIÇOS DE TECNOLOGIA DA INFORMAÇÃO"),
        Classification("62.0", "Atividades dos serviços de tecnologia da informação"),
        Classification("62.01-5", "Desenvolvimento de programas de computador sob encomenda"),
        Classification("62.02-3", "Desenvolvimento e licenciamento de programas de computador customizáveis"),
        Classification("62.03-1", "Desenvolvimento e licenciamento de programas de computador não-customizáveis"),
        Classification("62.04-0", "Consultoria em tecnologia da informação"),
        Classification("62.09-1", "Suporte técnico, manutenção e outros serviços em tecnologia da informação"),
        Classification("63", "ATIVIDADES DE PRESTAÇÃO DE SERVIÇOS DE INFORMAÇÃO"),
        Classification("63.1", "Tratamento de dados, hospedagem na internet e outras atividades relacionadas"),
        Classification(
            "63.11-9", "Tratamento de dados, provedores de serviços de aplicação e serviços de hospedagem na internet"
        ),
        Classification("63.19-4", "Portais, provedores de conteúdo e outros serviços de informação na internet"),
        Classification("63.9", "Outras atividades de prestação de serviços de informação"),
        Classification("63.91-7", "Agências de notícias"),
        Classification(
            "63.99-2", "Outras atividades de prestação de serviços de informação não especificadas anteriormente"
        ),
        Classification("K", "ATIVIDADES FINANCEIRAS, DE SEGUROS E SERVIÇOS RELACIONADOS"),
        Classification("64", "ATIVIDADES DE SERVIÇOS FINANCEIROS"),
        Classification("64.1", "Banco Central"),
        Classification("64.10-7", "Banco Central"),
        Classification("64.2", "Intermediação monetária - depósitos à vista"),
        Classification("64.21-2", "Bancos comerciais"),
        Classification("64.22-1", "Bancos múltiplos, com carteira comercial"),
        Classification("64.23-9", "Caixas econômicas"),
        Classification("64.24-7", "Crédito cooperativo"),
        Classification("64.3", "Intermediação não-monetária - outros instrumentos de captação"),
        Classification("64.31-0", "Bancos múltiplos, sem carteira comercial"),
        Classification("64.32-8", "Bancos de investimento"),
        Classification("64.33-6", "Bancos de desenvolvimento"),
        Classification("64.34-4", "Agências de fomento"),
        Classification("64.35-2", "Crédito imobiliário"),
        Classification("64.36-1", "Sociedades de crédito, financiamento e investimento - financeiras"),
        Classification("64.37-9", "Sociedades de crédito ao microempreendedor"),
        Classification("64.4", "Arrendamento mercantil"),
        Classification("64.40-9", "Arrendamento mercantil"),
        Classification("64.5", "Sociedades de capitalização"),
        Classification("64.50-6", "Sociedades de capitalização"),
        Classification("64.6", "Atividades de sociedades de participação"),
        Classification("64.61-1", "Holdings de instituições financeiras"),
        Classification("64.62-0", "Holdings de instituições não-financeiras"),
        Classification("64.63-8", "Outras sociedades de participação, exceto holdings"),
        Classification("64.7", "Fundos de investimento"),
        Classification("64.70-1", "Fundos de investimento"),
        Classification("64.9", "Atividades de serviços financeiros não especificadas anteriormente"),
        Classification("64.91-3", "Sociedades de fomento mercantil - factoring"),
        Classification("64.92-1", "Securitização de créditos"),
        Classification("64.93-0", "Administração de consórcios para aquisição de bens e direitos"),
        Classification("64.99-9", "Outras atividades de serviços financeiros não especificadas anteriormente"),
        Classification("65", "SEGUROS, RESSEGUROS, PREVIDÊNCIA COMPLEMENTAR E PLANOS DE SAÚDE"),
        Classification("65.1", "Seguros de vida e não-vida"),
        Classification("65.11-1", "Seguros de vida"),
        Classification("65.12-0", "Seguros não-vida"),
        Classification("65.2", "Seguros-saúde"),
        Classification("65.20-1", "Seguros-saúde"),
        Classification("65.3", "Resseguros"),
        Classification("65.30-8", "Resseguros"),
        Classification("65.4", "Previdência complementar"),
        Classification("65.41-3", "Previdência complementar fechada"),
        Classification("65.42-1", "Previdência complementar aberta"),
        Classification("65.5", "Planos de saúde"),
        Classification("65.50-2", "Planos de saúde"),
        Classification(
            "66", "ATIVIDADES AUXILIARES DOS SERVIÇOS FINANCEIROS, SEGUROS, PREVIDÊNCIA COMPLEMENTAR E PLANOS DE SAÚDE"
        ),
        Classification("66.1", "Atividades auxiliares dos serviços financeiros"),
        Classification("66.11-8", "Administração de bolsas e mercados de balcão organizados"),
        Classification(
            "66.12-6", "Atividades de intermediários em transações de títulos, valores mobiliários e mercadorias"
        ),
        Classification("66.13-4", "Administração de cartões de crédito"),
        Classification("66.19-3", "Atividades auxiliares dos serviços financeiros não especificadas anteriormente"),
        Classification("66.2", "Atividades auxiliares dos seguros, da previdência complementar e dos planos de saúde"),
        Classification("66.21-5", "Avaliação de riscos e perdas"),
        Classification("66.22-3", "Corretores e agentes de seguros, de planos de previdência complementar e de saúde"),
        Classification(
            "66.29-1",
            "Atividades auxiliares dos seguros, da previdência complementar e dos planos de saúde não especificadas anteriormente",
        ),
        Classification("66.3", "Atividades de administração de fundos por contrato ou comissão"),
        Classification("66.30-4", "Atividades de administração de fundos por contrato ou comissão"),
        Classification("L", "ATIVIDADES IMOBILIÁRIAS"),
        Classification("68", "ATIVIDADES IMOBILIÁRIAS"),
        Classification("68.1", "Atividades imobiliárias de imóveis próprios"),
        Classification("68.10-2", "Atividades imobiliárias de imóveis próprios"),
        Classification("68.2", "Atividades imobiliárias por contrato ou comissão"),
        Classification("68.21-8", "Intermediação na compra, venda e aluguel de imóveis"),
        Classification("68.22-6", "Gestão e administração da propriedade imobiliária"),
        Classification("M", "ATIVIDADES PROFISSIONAIS, CIENTÍFICAS E TÉCNICAS"),
        Classification("69", "ATIVIDADES JURÍDICAS, DE CONTABILIDADE E DE AUDITORIA"),
        Classification("69.1", "Atividades jurídicas"),
        Classification("69.11-7", "Atividades jurídicas, exceto cartórios"),
        Classification("69.12-5", "Cartórios"),
        Classification("69.2", "Atividades de contabilidade, consultoria e auditoria contábil e tributária"),
        Classification("69.20-6", "Atividades de contabilidade, consultoria e auditoria contábil e tributária"),
        Classification("70", "ATIVIDADES DE SEDES DE EMPRESAS E DE CONSULTORIA EM GESTÃO EMPRESARIAL"),
        Classification("70.1", "Sedes de empresas e unidades administrativas locais"),
        Classification("70.10-7", "Sedes de empresas e unidades administrativas locais"),
        Classification("70.2", "Atividades de consultoria em gestão empresarial"),
        Classification("70.20-4", "Atividades de consultoria em gestão empresarial"),
        Classification("71", "SERVIÇOS DE ARQUITETURA E ENGENHARIA; TESTES E ANÁLISES TÉCNICAS"),
        Classification("71.1", "Serviços de arquitetura e engenharia e atividades técnicas relacionadas"),
        Classification("71.11-1", "Serviços de arquitetura"),
        Classification("71.12-0", "Serviços de engenharia"),
        Classification("71.19-7", "Atividades técnicas relacionadas à arquitetura e engenharia"),
        Classification("71.2", "Testes e análises técnicas"),
        Classification("71.20-1", "Testes e análises técnicas"),
        Classification("72", "PESQUISA E DESENVOLVIMENTO CIENTÍFICO"),
        Classification("72.1", "Pesquisa e desenvolvimento experimental em ciências físicas e naturais"),
        Classification("72.10-0", "Pesquisa e desenvolvimento experimental em ciências físicas e naturais"),
        Classification("72.2", "Pesquisa e desenvolvimento experimental em ciências sociais e humanas"),
        Classification("72.20-7", "Pesquisa e desenvolvimento experimental em ciências sociais e humanas"),
        Classification("73", "PUBLICIDADE E PESQUISA DE MERCADO"),
        Classification("73.1", "Publicidade"),
        Classification("73.11-4", "Agências de publicidade"),
        Classification("73.12-2", "Agenciamento de espaços para publicidade, exceto em veículos de comunicação"),
        Classification("73.19-0", "Atividades de publicidade não especificadas anteriormente"),
        Classification("73.2", "Pesquisas de mercado e de opinião pública"),
        Classification("73.20-3", "Pesquisas de mercado e de opinião pública"),
        Classification("74", "OUTRAS ATIVIDADES PROFISSIONAIS, CIENTÍFICAS E TÉCNICAS"),
        Classification("74.1", "Design e decoração de interiores"),
        Classification("74.10-2", "Design e decoração de interiores"),
        Classification("74.2", "Atividades fotográficas e similares"),
        Classification("74.20-0", "Atividades fotográficas e similares"),
        Classification("74.9", "Atividades profissionais, científicas e técnicas não especificadas anteriormente"),
        Classification("74.90-1", "Atividades profissionais, científicas e técnicas não especificadas anteriormente"),
        Classification("75", "ATIVIDADES VETERINÁRIAS"),
        Classification("75.0", "Atividades veterinárias"),
        Classification("75.00-1", "Atividades veterinárias"),
        Classification("N", "ATIVIDADES ADMINISTRATIVAS E SERVIÇOS COMPLEMENTARES"),
        Classification("77", "ALUGUÉIS NÃO-IMOBILIÁRIOS E GESTÃO DE ATIVOS INTANGÍVEIS NÃO-FINANCEIROS"),
        Classification("77.1", "Locação de meios de transporte sem condutor"),
        Classification("77.11-0", "Locação de automóveis sem condutor"),
        Classification("77.19-5", "Locação de meios de transporte, exceto automóveis, sem condutor"),
        Classification("77.2", "Aluguel de objetos pessoais e domésticos"),
        Classification("77.21-7", "Aluguel de equipamentos recreativos e esportivos"),
        Classification("77.22-5", "Aluguel de fitas de vídeo, DVDs e similares"),
        Classification("77.23-3", "Aluguel de objetos do vestuário, jóias e acessórios"),
        Classification("77.29-2", "Aluguel de objetos pessoais e domésticos não especificados anteriormente"),
        Classification("77.3", "Aluguel de máquinas e equipamentos sem operador"),
        Classification("77.31-4", "Aluguel de máquinas e equipamentos agrícolas sem operador"),
        Classification("77.32-2", "Aluguel de máquinas e equipamentos para construção sem operador"),
        Classification("77.33-1", "Aluguel de máquinas e equipamentos para escritório"),
        Classification("77.39-0", "Aluguel de máquinas e equipamentos não especificados anteriormente"),
        Classification("77.4", "Gestão de ativos intangíveis não-financeiros"),
        Classification("77.40-3", "Gestão de ativos intangíveis não-financeiros"),
        Classification("78", "SELEÇÃO, AGENCIAMENTO E LOCAÇÃO DE MÃO-DE-OBRA"),
        Classification("78.1", "Seleção e agenciamento de mão-de-obra"),
        Classification("78.10-8", "Seleção e agenciamento de mão-de-obra"),
        Classification("78.2", "Locação de mão-de-obra temporária"),
        Classification("78.20-5", "Locação de mão-de-obra temporária"),
        Classification("78.3", "Fornecimento e gestão de recursos humanos para terceiros"),
        Classification("78.30-2", "Fornecimento e gestão de recursos humanos para terceiros"),
        Classification("79", "AGÊNCIAS DE VIAGENS, OPERADORES TURÍSTICOS E SERVIÇOS DE RESERVAS"),
        Classification("79.1", "Agências de viagens e operadores turísticos"),
        Classification("79.11-2", "Agências de viagens"),
        Classification("79.12-1", "Operadores turísticos"),
        Classification("79.9", "Serviços de reservas e outros serviços de turismo não especificados anteriormente"),
        Classification("79.90-2", "Serviços de reservas e outros serviços de turismo não especificados anteriormente"),
        Classification("80", "ATIVIDADES DE VIGILÂNCIA, SEGURANÇA E INVESTIGAÇÃO"),
        Classification("80.1", "Atividades de vigilância, segurança privada e transporte de valores"),
        Classification("80.11-1", "Atividades de vigilância e segurança privada"),
        Classification("80.12-9", "Atividades de transporte de valores"),
        Classification("80.2", "Atividades de monitoramento de sistemas de segurança"),
        Classification("80.20-0", "Atividades de monitoramento de sistemas de segurança"),
        Classification("80.3", "Atividades de investigação particular"),
        Classification("80.30-7", "Atividades de investigação particular"),
        Classification("81", "SERVIÇOS PARA EDIFÍCIOS E ATIVIDADES PAISAGÍSTICAS"),
        Classification("81.1", "Serviços combinados para apoio a edifícios"),
        Classification("81.11-7", "Serviços combinados para apoio a edifícios, exceto condomínios prediais"),
        Classification("81.12-5", "Condomínios prediais"),
        Classification("81.2", "Atividades de limpeza"),
        Classification("81.21-4", "Limpeza em prédios e em domicílios"),
        Classification("81.22-2", "Imunização e controle de pragas urbanas"),
        Classification("81.29-0", "Atividades de limpeza não especificadas anteriormente"),
        Classification("81.3", "Atividades paisagísticas"),
        Classification("81.30-3", "Atividades paisagísticas"),
        Classification(
            "82",
            "SERVIÇOS DE ESCRITÓRIO, DE APOIO ADMINISTRATIVO E OUTROS SERVIÇOS PRESTADOS PRINCIPALMENTE ÀS EMPRESAS",
        ),
        Classification("82.1", "Serviços de escritório e apoio administrativo"),
        Classification("82.11-3", "Serviços combinados de escritório e apoio administrativo"),
        Classification(
            "82.19-9", "Fotocópias, preparação de documentos e outros serviços especializados de apoio administrativo"
        ),
        Classification("82.2", "Atividades de teleatendimento"),
        Classification("82.20-2", "Atividades de teleatendimento"),
        Classification("82.3", "Atividades de organização de eventos, exceto culturais e esportivos"),
        Classification("82.30-0", "Atividades de organização de eventos, exceto culturais e esportivos"),
        Classification("82.9", "Outras atividades de serviços prestados principalmente às empresas"),
        Classification("82.91-1", "Atividades de cobrança e informações cadastrais"),
        Classification("82.92-0", "Envasamento e empacotamento sob contrato"),
        Classification(
            "82.99-7", "Atividades de serviços prestados principalmente às empresas não especificadas anteriormente"
        ),
        Classification("O", "ADMINISTRAÇÃO PÚBLICA, DEFESA E SEGURIDADE SOCIAL"),
        Classification("84", "ADMINISTRAÇÃO PÚBLICA, DEFESA E SEGURIDADE SOCIAL"),
        Classification("84.1", "Administração do estado e da política econômica e social"),
        Classification("84.11-6", "Administração pública em geral"),
        Classification(
            "84.12-4", "Regulação das atividades de saúde, educação, serviços culturais e outros serviços sociais"
        ),
        Classification("84.13-2", "Regulação das atividades econômicas"),
        Classification("84.2", "Serviços coletivos prestados pela administração pública"),
        Classification("84.21-3", "Relações exteriores"),
        Classification("84.22-1", "Defesa"),
        Classification("84.23-0", "Justiça"),
        Classification("84.24-8", "Segurança e ordem pública"),
        Classification("84.25-6", "Defesa Civil"),
        Classification("84.3", "Seguridade social obrigatória"),
        Classification("84.30-2", "Seguridade social obrigatória"),
        Classification("P", "EDUCAÇÃO"),
        Classification("85", "EDUCAÇÃO"),
        Classification("85.1", "Educação infantil e ensino fundamental"),
        Classification("85.11-2", "Educação infantil - creche"),
        Classification("85.12-1", "Educação infantil - pré-escola"),
        Classification("85.13-9", "Ensino fundamental"),
        Classification("85.2", "Ensino médio"),
        Classification("85.20-1", "Ensino médio"),
        Classification("85.3", "Educação superior"),
        Classification("85.31-7", "Educação superior - graduação"),
        Classification("85.32-5", "Educação superior - graduação e pós-graduação"),
        Classification("85.33-3", "Educação superior - pós-graduação e extensão"),
        Classification("85.4", "Educação profissional de nível técnico e tecnológico"),
        Classification("85.41-4", "Educação profissional de nível técnico"),
        Classification("85.42-2", "Educação profissional de nível tecnológico"),
        Classification("85.5", "Atividades de apoio à educação"),
        Classification("85.50-3", "Atividades de apoio à educação"),
        Classification("85.9", "Outras atividades de ensino"),
        Classification("85.91-1", "Ensino de esportes"),
        Classification("85.92-9", "Ensino de arte e cultura"),
        Classification("85.93-7", "Ensino de idiomas"),
        Classification("85.99-6", "Atividades de ensino não especificadas anteriormente"),
        Classification("Q", "SAÚDE HUMANA E SERVIÇOS SOCIAIS"),
        Classification("86", "ATIVIDADES DE ATENÇÃO À SAÚDE HUMANA"),
        Classification("86.1", "Atividades de atendimento hospitalar"),
        Classification("86.10-1", "Atividades de atendimento hospitalar"),
        Classification("86.2", "Serviços móveis de atendimento a urgências e de remoção de pacientes"),
        Classification("86.21-6", "Serviços móveis de atendimento a urgências"),
        Classification(
            "86.22-4", "Serviços de remoção de pacientes, exceto os serviços móveis de atendimento a urgências"
        ),
        Classification("86.3", "Atividades de atenção ambulatorial executadas por médicos e odontólogos"),
        Classification("86.30-5", "Atividades de atenção ambulatorial executadas por médicos e odontólogos"),
        Classification("86.4", "Atividades de serviços de complementação diagnóstica e terapêutica"),
        Classification("86.40-2", "Atividades de serviços de complementação diagnóstica e terapêutica"),
        Classification("86.5", "Atividades de profissionais da área de saúde, exceto médicos e odontólogos"),
        Classification("86.50-0", "Atividades de profissionais da área de saúde, exceto médicos e odontólogos"),
        Classification("86.6", "Atividades de apoio à gestão de saúde"),
        Classification("86.60-7", "Atividades de apoio à gestão de saúde"),
        Classification("86.9", "Atividades de atenção à saúde humana não especificadas anteriormente"),
        Classification("86.90-9", "Atividades de atenção à saúde humana não especificadas anteriormente"),
        Classification(
            "87",
            "ATIVIDADES DE ATENÇÃO À SAÚDE HUMANA INTEGRADAS COM ASSISTÊNCIA SOCIAL, PRESTADAS EM RESIDÊNCIAS COLETIVAS E PARTICULARES",
        ),
        Classification(
            "87.1",
            "Atividades de assistência a idosos, deficientes físicos, imunodeprimidos e convalescentes, e de infra-estrutura e apoio a pacientes prestadas em residências coletivas e particulares",
        ),
        Classification(
            "87.11-5",
            "Atividades de assistência a idosos, deficientes físicos, imunodeprimidos e convalescentes prestadas em residências coletivas e particulares",
        ),
        Classification(
            "87.12-3", "Atividades de fornecimento de infra-estrutura de apoio e assistência a paciente no domicílio"
        ),
        Classification(
            "87.2",
            "Atividades de assistência psicossocial e à saúde a portadores de distúrbios psíquicos, deficiência mental e dependência química",
        ),
        Classification(
            "87.20-4",
            "Atividades de assistência psicossocial e à saúde a portadores de distúrbios psíquicos, deficiência mental e dependência química",
        ),
        Classification("87.3", "Atividades de assistência social prestadas em residências coletivas e particulares"),
        Classification("87.30-1", "Atividades de assistência social prestadas em residências coletivas e particulares"),
        Classification("88", "SERVIÇOS DE ASSISTÊNCIA SOCIAL SEM ALOJAMENTO"),
        Classification("88.0", "Serviços de assistência social sem alojamento"),
        Classification("88.00-6", "Serviços de assistência social sem alojamento"),
        Classification("R", "ARTES, CULTURA, ESPORTE E RECREAÇÃO"),
        Classification("90", "ATIVIDADES ARTÍSTICAS, CRIATIVAS E DE ESPETÁCULOS"),
        Classification("90.0", "Atividades artísticas, criativas e de espetáculos"),
        Classification("90.01-9", "Artes cênicas, espetáculos e atividades complementares"),
        Classification("90.02-7", "Criação artística"),
        Classification("90.03-5", "Gestão de espaços para artes cênicas, espetáculos e outras atividades artísticas"),
        Classification("91", "ATIVIDADES LIGADAS AO PATRIMÔNIO CULTURAL E AMBIENTAL"),
        Classification("91.0", "Atividades ligadas ao patrimônio cultural e ambiental"),
        Classification("91.01-5", "Atividades de bibliotecas e arquivos"),
        Classification(
            "91.02-3",
            "Atividades de museus e de exploração, restauração artística e conservação de lugares e prédios históricos e atrações similares",
        ),
        Classification(
            "91.03-1",
            "Atividades de jardins botânicos, zoológicos, parques nacionais, reservas ecológicas e áreas de proteção ambiental",
        ),
        Classification("92", "ATIVIDADES DE EXPLORAÇÃO DE JOGOS DE AZAR E APOSTAS"),
        Classification("92.0", "Atividades de exploração de jogos de azar e apostas"),
        Classification("92.00-3", "Atividades de exploração de jogos de azar e apostas"),
        Classification("93", "ATIVIDADES ESPORTIVAS E DE RECREAÇÃO E LAZER"),
        Classification("93.1", "Atividades esportivas"),
        Classification("93.11-5", "Gestão de instalações de esportes"),
        Classification("93.12-3", "Clubes sociais, esportivos e similares"),
        Classification("93.13-1", "Atividades de condicionamento físico"),
        Classification("93.19-1", "Atividades esportivas não especificadas anteriormente"),
        Classification("93.2", "Atividades de recreação e lazer"),
        Classification("93.21-2", "Parques de diversão e parques temáticos"),
        Classification("93.29-8", "Atividades de recreação e lazer não especificadas anteriormente"),
        Classification("S", "OUTRAS ATIVIDADES DE SERVIÇOS"),
        Classification("94", "ATIVIDADES DE ORGANIZAÇÕES ASSOCIATIVAS"),
        Classification("94.1", "Atividades de organizações associativas patronais, empresariais e profissionais"),
        Classification("94.11-1", "Atividades de organizações associativas patronais e empresariais"),
        Classification("94.12-0", "Atividades de organizações associativas profissionais"),
        Classification("94.2", "Atividades de organizações sindicais"),
        Classification("94.20-1", "Atividades de organizações sindicais"),
        Classification("94.3", "Atividades de associações de defesa de direitos sociais"),
        Classification("94.30-8", "Atividades de associações de defesa de direitos sociais"),
        Classification("94.9", "Atividades de organizações associativas não especificadas anteriormente"),
        Classification("94.91-0", "Atividades de organizações religiosas"),
        Classification("94.92-8", "Atividades de organizações políticas"),
        Classification("94.93-6", "Atividades de organizações associativas ligadas à cultura e à arte"),
        Classification("94.99-5", "Atividades associativas não especificadas anteriormente"),
        Classification(
            "95",
            "REPARAÇÃO E MANUTENÇÃO DE EQUIPAMENTOS DE INFORMÁTICA E COMUNICAÇÃO E DE OBJETOS PESSOAIS E DOMÉSTICOS",
        ),
        Classification("95.1", "Reparação e manutenção de equipamentos de informática e comunicação"),
        Classification("95.11-8", "Reparação e manutenção de computadores e de equipamentos periféricos"),
        Classification("95.12-6", "Reparação e manutenção de equipamentos de comunicação"),
        Classification("95.2", "Reparação e manutenção de objetos e equipamentos pessoais e domésticos"),
        Classification(
            "95.21-5", "Reparação e manutenção de equipamentos eletroeletrônicos de uso pessoal e doméstico"
        ),
        Classification(
            "95.29-1",
            "Reparação e manutenção de objetos e equipamentos pessoais e domésticos não especificados anteriormente",
        ),
        Classification("96", "OUTRAS ATIVIDADES DE SERVIÇOS PESSOAIS"),
        Classification("96.0", "Outras atividades de serviços pessoais"),
        Classification("96.01-7", "Lavanderias, tinturarias e toalheiros"),
        Classification("96.02-5", "Cabeleireiros e outras atividades de tratamento de beleza"),
        Classification("96.03-3", "Atividades funerárias e serviços relacionados"),
        Classification("96.09-2", "Atividades de serviços pessoais não especificadas anteriormente"),
        Classification("T", "SERVIÇOS DOMÉSTICOS"),
        Classification("97", "SERVIÇOS DOMÉSTICOS"),
        Classification("97.0", "Serviços domésticos"),
        Classification("97.00-5", "Serviços domésticos"),
        Classification("U", "ORGANISMOS INTERNACIONAIS E OUTRAS INSTITUIÇÕES EXTRATERRITORIAIS"),
        Classification("99", "ORGANISMOS INTERNACIONAIS E OUTRAS INSTITUIÇÕES EXTRATERRITORIAIS"),
        Classification("99.0", "Organismos internacionais e outras instituições extraterritoriais"),
        Classification("99.00-8", "Organismos internacionais e outras instituições extraterritoriais"),
    ],
)
