name: Publish
on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  publish:
    if: startsWith(github.ref, 'refs/tags')
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/pyisic
    permissions:
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python with version 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Install pypa/build
      run: |
        python -m pip install build --user
    - name: Build a binary wheel and a source tarball
      run: |
        python -m build --sdist --wheel --outdir dist/
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
